### DISCUSSION TITLE
Unable to Add IP Address to Interface with Ansible Modules

### DISCUSSION THREAD

**Discussion by eramnes** [netbox-community/netbox#10573] [Q&A]
Greetings:

I am trying to add an IP address to a VM interface using the Netbox Ansible modules, but no matter what I try I always receive a "Failed to establish connection to Netbox API" error.

I have verified:

- the Netbox server is up and I can log in via browser
- I am able to access the API using the token I've created
- the certificate on the Netbox instance is trusted using "openssl s_client -connect netbox.url:443 -showcerts 2>&1 | head" (I have also tried disabling certificate verification entirely)
- the host where the playbook is running can access the Netbox API by running a test query of "curl -X GET -H "Authorization: Token abcd" https://netbox.url/api/ipam/prefixes/ -H "accept: application/json"    {"count":0,"next":null,"previous":null,"results":[]}".  This test returns results successfully.

Here is the playbook, minus some of the prior operations which return the next available IP from Infoblox and create a host record in Infoblox:

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create IP address in netbox and assign to interface
      netbox_ip_address:
        netbox_url: https://netbox.url
        netbox_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/kv/automation/data/ansible-netbox-tst-token/:token auth_method=approle') }}"
        data:
          address: "{{ host.ipv4addrs[0].ipv4addr }}"
          vrf: "{{ vlan_from_netbox }}"
          dns_name:  "{{ host.ipv4addrs[0].host }}"
          interface:
            name: tst_interface
            virtual_machine: interfacetst
```
Here is the results when running the playbook with -vvvv:

```
TASK [Create IP address in netbox and assign to interface] *********************
task path: /var/lib/go-agent/pipelines/nios-test/ansible-infoblox-nios-tst-nb.yml:38
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: go
<127.0.0.1> EXEC /bin/sh -c 'echo ~go && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/go/.ansible/tmp `"&& mkdir "` echo /var/go/.ansible/tmp/ansible-tmp-1664980412.785029-687657-66584688212957 `" && echo ansible-tmp-1664980412.785029-687657-66584688212957="` echo /var/go/.ansible/tmp/ansible-tmp-1664980412.785029-687657-66584688212957 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/net_tools/netbox/netbox_ip_address.py
<127.0.0.1> PUT /var/go/.ansible/tmp/ansible-local-687621r_ztnoir/tmpvb41c0th TO /var/go/.ansible/tmp/ansible-tmp-1664980412.785029-687657-66584688212957/AnsiballZ_netbox_ip_address.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/go/.ansible/tmp/ansible-tmp-1664980412.785029-687657-66584688212957/ /var/go/.ansible/tmp/ansible-tmp-1664980412.785029-687657-66584688212957/AnsiballZ_netbox_ip_address.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/libexec/platform-python /var/go/.ansible/tmp/ansible-tmp-1664980412.785029-687657-66584688212957/AnsiballZ_netbox_ip_address.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/go/.ansible/tmp/ansible-tmp-1664980412.785029-687657-66584688212957/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_netbox_ip_address_payload_evm6hvj1/ansible_netbox_ip_address_payload.zip/ansible/modules/net_tools/netbox/netbox_ip_address.py", line 280, in main
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "address": "172.16.134.158",
                "dns_name": "interfacetst.netbox.url",
                "interface": {
                    "name": "tst_interface",
                    "virtual_machine": "interfacetst"
                },
                "vrf": "VLAN134"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.url",
            "state": "present",
        }
    }
}

MSG:

Failed to establish connection to Netbox API
```

We are using Netbox v 3.3.4 and I am using pynetbox 6.6.2 with the 3.8.0 version of the Netbox collection installed via ansible-galaxy.  The ansible version is 2.9.27 on RHEL 8.  The packaging module is also installed via pip as mentioned in the README for ansible <2.10.

Can someone point me to where I'm going wrong?  Is it because ansible is stuck at 2.9? It seems like everything should connect without issues to me.

Thanks!
