### DISCUSSION TITLE
Error when importing custom fields

### DISCUSSION THREAD

**Discussion by harryjr** [netbox-community/netbox#12259] [Help Wanted!]
Hello,

I am sure this is not a formatting issue.  I previously exported all of my custom fields into CSV.  After deleting them, I have tried to import them back again.  I have also tried to create a simple YAML file with one object to import, but get the same error:

<class 'AttributeError'>

'NoneType' object has no attribute 'app_label'

Python version: 3.9.13
NetBox version: 3.4.5

**Comment by harryjr** [comment]
Here is the simple .yaml file I am using to test:

VLAN_Domain_ID:
  name: VLAN_Domain_ID
  type: text
  description: ID for VLAN Domain
  required: true
  search_weight: 0
  filter_logic: Loose
  ui_visibility: read-write
  content_types: ipam.vlangroup

**Reply by sisayhaile** [reply]
I run into a similar issue when importing the custom field. 
<class 'AttributeError'>

'NoneType' object has no attribute 'app_label'

Python version: 3.10.6
NetBox version: 3.5.3

**Reply by gurubert** [reply]
+1

**Reply by abhi1693** [reply]
I've not tested it but content types should be a list

**Reply by candlerb** [reply]
> Here is the simple .yaml file I am using to test

YAML is indentation-sensitive. Please edit your post and put three backticks (` ``` `) on a line of their own, before and after the yaml, so that it can be copied accurately.

However, it seems to me that the main problem is the spurious outer tag (the first line `VLAN_Domain_ID:`).  The following YAML works for me with Netbox v3.6.0; I also had to add "weight", and change "Loose" to "loose", but there were helpful error messages telling me when these were wrong.

```yaml
name: VLAN_Domain_ID
type: text
description: ID for VLAN Domain
required: true
weight: 100
search_weight: 0
filter_logic: loose
ui_visibility: read-write
content_types: ipam.vlangroup
```
