### DISCUSSION TITLE
Server Error

### DISCUSSION THREAD

**Discussion by TrixaFett** [netbox-community/netbox#12891] [Help Wanted!]
Have a Production and a test Netbox_Docker.
I am trying to update my prod Netbox to newest, but on my Test Netbox i get an Server Error when logging in:
"""
<class 'django.contrib.auth.models.User.MultipleObjectsReturned'>

get() returned more than one User -- it returned 2!

Python version: 3.10.6
NetBox version: 3.4.6
"""
I am using AD integration and it has worked before. I have no problems logging into the Production Enviroment

**Comment by candlerb** [comment]
It looks like there's some problem with your LDAP config then, so you'll have to start homing in on this:
* What versions of Netbox are the test and production instances? You said you are trying to "update": what versions are you moving from and to? You show 3.4.6 on the test server: is this the same version as you're running on prod, or is this after you've done the upgrade?
* Are they pointing to the same instance of AD, or different ones?
* What's the content of ldap_configuration.py on both systems?

**Reply by TrixaFett** [reply]
Its the same versions on prod and test. I want to update newest release.
The LDAP config has not changed and are the same on Test and Prod. also pointing to the same. (and it used to work.)
I get to the login page but when I try to log in i get the Error

**Reply by candlerb** [reply]
Just to be clear, you're saying that the prod server works, but the test server doesn't, despite having the same version of Netbox?

What else is different between these two systems?

> and it used to work

Have you any idea what has changed in the mean time?

On the failing system, try this SQL query (usually `sudo -u postgres psql netbox` will get you a SQL prompt)

```
select username,count(*) from auth_user group by username having count(*) > 1;
```

It *shouldn't* be possible to have duplicate users in this table, but maybe you are missing an index. Try `\d auth_user` on both systems and compare the output. Mine includes the following indexes:

```
Indexes:
    "auth_user_pkey" PRIMARY KEY, btree (id)
    "auth_user_username_key" UNIQUE CONSTRAINT, btree (username)    << this should prevent duplicates
    "auth_user_username_6821ab7c_like" btree (username varchar_pattern_ops)
```

Oh, and here's a slightly different query you could try too:

```
select lower(username),count(*) from auth_user group by lower(username) having count(*) > 1;
```

**Reply by candlerb** [reply]
It would also be helpful if you could show the full backtrace. Either set ADMINS and EMAIL in configuration.py (in which case it should be E-mailed out), or set DEBUG=True (in which case it should be downloadable from the web UI)

**Reply by TrixaFett** [reply]
i do LDAP through docker-compose.override.yml on Test
here is mine:

```
version: '3.4'
services:
  netbox: &netbox
    environment:
      AUTH_LDAP_BIND_PASSWORD: "****"
      AUTH_LDAP_SERVER_URI: "****"
      AUTH_LDAP_BIND_DN: "****"
      AUTH_LDAP_USER_SEARCH_BASEDN: "****"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "****"
      AUTH_LDAP_REQUIRE_GROUP_DN: "****"
      AUTH_LDAP_IS_ADMIN_DN: "****"
      AUTH_LDAP_IS_SUPERUSER_DN: "****"
      LDAP_IGNORE_CERT_ERRORS: "true"
      REMOTE_AUTH_ENABLED: "true"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      MAPS_URL: "https://maps.google.com/?q="
      RELEASE_CHECK_URL:
      CHANGELOG_RETENTION: 1460
    restart: unless-stopped
    ports:
    - 8881:8080
  netbox-worker:
    <<: *netbox
    labels: []
    ports: []
  netbox-housekeeping:
    <<: *netbox
    labels: []
    ports: []
```
