### DISCUSSION TITLE
How to model BladeChassis -> Switch module (interfaces) -> Server module in device bay?

### DISCUSSION THREAD

**Discussion by mikasaari** [netbox-community/netbox#13497] [Help Wanted!] [answered]
Hi,
   
  I am using the Netbox version 3.5.4. 

  Question:
 How should I model my HPE C7000 Blade Chassis which has switch module inserted in so the server in device bay would inherit the interfaces and not the Blade Chassis?

  Explained a bit more:
    My HPE c7000 Blade Chassis has two HPE switch modules inserted in. Each switch module adds one interface to the actual server, so in my case each server has 2 interfaces. Now when I create device type "c7000" and module type "hpe switch". Then create new device and module and install the module to the device, I see all the interfaces shown on the c7000. Is there way of modeling this kind of pass-through system, so the proper interfaces (one per switch) would be shown in the actual server device? 

  Thanks a lot!

**Comment by PurplePetrus** [comment, marked as answer]
Hi, 

I had a similar case in the past.

in a similar context (server with added interface cards) i constructed the following model. 

i created 2 object types.
- the server with module bays (device-type)
- the interface cards as modules (module-type)

I added the server as a 'device type' with only the interfaces added to it that are fixed for that device (idrac/ilo, management interfaces,...). On top of that i have added module bays for every slot where you can add a physical module. Make sure to give every module bay a position value. This will help in a later stage with the naming when adding modules to the module bays.

next i created a module type for my interface card. on that module type i've added the interfaces that are part of that module. To get some dynamic naming (in case you need to put multiple modules of the same type to the same device) i suggest naming the interfaces with the {module} placeholder. (e.g. Eth-{module}/0 ) This is the part where the position value of the module bay will come in play.

When creating a server of that type, i can assign the necessary modules to the module bays. When adding the modules, you'll have the option to "replicate components". This option will add the interfaces of your module to the interfaces of your device, as if they are part of that device. When you remove the module, the interfaces will also be removed from the device since they are part of the module and not of the device directly. 

I hope this could answer your question.

**Reply by mikasaari** [reply]
Hi,

  Sorry for late  answer. This is exactly what I was looking for. I found out that it probably is best to connect the device (module) interfaces (iLO, and all those you explained in your explanation) to the blade chassis switch interface with "Direct Attach Copper", and then connect the actual switch with normal cable. This way I think it is following normal world as much as possible. 

  Thanks a lot for great explanation!

**Comment by SunilSaraswat** [comment]
Hi @PurplePetrus,

Can you pl share the device-type & module-type yaml file for reference.

**Comment by mikasaari** [comment]
Hi,

  Just exported c7000 related device types and module types I am using. These are not the best I have noticed, but will tweak them one day. Currently they are just fine for my purpose. 

**Blade System C7000**
```
manufacturer: HPE
model: BladeSystem c7000
slug: hpe-bladesystem-c7000
default_platform: null
part_number: ''
u_height: 10.0
is_full_depth: true
subdevice_role: parent
airflow: ''
comments: ''
weight: null
weight_unit: ''
power-ports:
- name: PS1
  type: iec-60320-c20
  maximum_draw: 2650
  allocated_draw: null
  label: ''
  description: ''
- name: PS2
  type: iec-60320-c20
  maximum_draw: 2650
  allocated_draw: null
  label: ''
  description: ''
- name: PS3
  type: iec-60320-c20
  maximum_draw: 2650
  allocated_draw: null
  label: ''
  description: ''
- name: PS4
  type: iec-60320-c20
  maximum_draw: 2650
  allocated_draw: null
  label: ''
  description: ''
- name: PS5
  type: iec-60320-c20
  maximum_draw: 2650
  allocated_draw: null
  label: ''
  description: ''
- name: PS6
  type: iec-60320-c20
  maximum_draw: 2650
  allocated_draw: null
  label: ''
  description: ''
module-bays:
- name: Interconnect Bay 01
  label: Interconnect Bay 01
  position: '1'
  description: ''
- name: Interconnect Bay 02
  label: Interconnect Bay 02
  position: '2'
  description: ''
- name: Interconnect Bay 03
  label: Interconnect Bay 03
  position: '3'
  description: ''
- name: Interconnect Bay 04
  label: Interconnect Bay 04
  position: '4'
  description: ''
- name: Interconnect Bay 05
  label: Interconnect Bay 05
  position: '5'
  description: ''
- name: Interconnect Bay 06
  label: Interconnect Bay 06
  position: '6'
  description: ''
- name: Interconnect Bay 07
  label: Interconnect Bay 07
  position: '7'
  description: ''
- name: Interconnect Bay 08
  label: Interconnect Bay 08
  position: '8'
  description: ''
- name: Onboad Administrator (left)
  label: Onboad Administrator (left)
  position: '9'
  description: ''
- name: Onboad Administrator (right)
  label: Onboad Administrator (right)
  position: '10'
  description: ''
device-bays:
- name: Device Bay 1
  label: ''
  description: ''
- name: Device Bay 2
  label: ''
  description: ''
- name: Device Bay 3
  label: ''
  description: ''
- name: Device Bay 4
  label: ''
  description: ''
- name: Device Bay 5
  label: ''
  description: ''
- name: Device Bay 6
  label: ''
  description: ''
- name: Device Bay 7
  label: ''
  description: ''
- name: Device Bay 8
  label: ''
  description: ''
- name: Device Bay 9
  label: ''
  description: ''
- name: Device Bay 10
  label: ''
  description: ''
- name: Device Bay 11
  label: ''
  description: ''
- name: Device Bay 12
  label: ''
  description: ''
- name: Device Bay 13
  label: ''
  description: ''
- name: Device Bay 14
  label: ''
  description: ''
- name: Device Bay 15
  label: ''
  description: ''
- name: Device Bay 16
  label: ''
  description: ''

```

**Onboard Administrator**
```
manufacturer: HPE
model: HP Onboard Administrator with KVM
part_number: 456204-B21
comments: ''
weight: 0.2
weight_unit: kg
interfaces:
- name: iLO {module}/01
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: iLO
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/02
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/03
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/04
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/05
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/06
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/07
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/08
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/09
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/10
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/11
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/12
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/13
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/14
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/15
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/16
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: iLO {module}/Uplink
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
```

**BL460c Gen10**
```
manufacturer: HPE
model: BL460c Gen10
slug: bl460c-gen10
default_platform: null
part_number: 863442-B21
u_height: 0.0
is_full_depth: false
subdevice_role: child
airflow: ''
comments: ''
weight: 6.3
weight_unit: kg
```

**Virtual Connect Flex-10/10D**
```
manufacturer: HPE
model: Virtual Connect Flex-10/10D
part_number: 638526-B21
comments: ''
weight: null
weight_unit: ''
interfaces:
- name: 10G {module}/01
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/02
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/03
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/04
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/05
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/06
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/07
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/08
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/09
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/10
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/11
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/12
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/13
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/14
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/15
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: 10G {module}/16
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: CrossConnect {module}/01
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: CrossConnect {module}/02
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: CrossConnect {module}/03
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: CrossConnect {module}/04
  type: 10gbase-kr
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/01
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/02
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/03
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/04
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/05
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/06
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/07
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/08
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/09
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
- name: UP {module}/10
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
```
