### DISCUSSION TITLE
'VirtualMachine' object has no attribute 'oob_ip_id'

### DISCUSSION THREAD

**Discussion by abhijitsharma1010** [netbox-community/netbox#13652] [General]
After the latest when we click on any ip address from the ipam section or from change log then we are getting this error. 
Any help will be very much appreciated. 
![11](https://github.com/netbox-community/netbox/assets/44794851/27921645-bf9d-43b3-999a-c4e655bcb120)

**Comment by abhijitsharma1010** [comment]
This resolved the issue.
https://github.com/netbox-community/netbox/pull/13621/files/0f1247c6ef06847940a4e5fcbabfc05248e34867#diff-b12db49b7b31202cc34428c1dbdf443ae9abb72547c0445e10497cee67698888

**Comment by kovacs-andras** [comment]
Many thanks! Same story here with the latest release (2.7.0) of netbox-docker.
Until there is no new release, I fixed temporarily mine with the `docker-compose.override.yml` like:
```
services:
  netbox:
    # https://github.com/netbox-community/netbox/pull/13621/files
    volumes:
      - /opt/netbox-docker/fix_13621_ip.py:/opt/netbox/netbox/ipam/models/ip.py:ro
```
I wish I've seen your discussion earlier, it could save me the debugging...
