### DISCUSSION TITLE
Device Type Bulk Import with custom fields

### DISCUSSION THREAD

**Discussion by jayGG83** [netbox-community/netbox#13751] [Q&A] [answered]
Hello,
I'm trying to do device type import from a YAML file. Is it possible to include also the device type custom fields?
I tried:
```
manufacturer: value
model: value
slug: value
u_height: value
custom_fields:
  custom_field_name: value
  custom_field_name: value
```
also: 
```
manufacturer: value
model: value
slug: value
u_height: value
custom_fields:
  - custom_field_name: value
  - custom_field_name: value
```
I also tried setting cf_ before the field name with no luck.
None of them worked. Any ideas?

**Comment by candlerb** [comment]
Netbox version?

With netbox 3.6.1, and a text custom field called "foo", the following works for me:

```
manufacturer: Unknown
model: zzzz
slug: zzzz
u_height: 0
cf_foo: bar
```

After import:

![image](https://github.com/netbox-community/netbox/assets/44789/c43174b1-ef70-4356-b027-e03f95b8b2e8)

**Reply by jayGG83** [reply]
Oh, my version is v3.5.4

**Reply by jayGG83** [reply]
I tried this with my version and didn't work:
```
---
manufacturer: Ericsson
model: ANT2 A 0.6 80 HP 2
slug: ant2-a-0-6-80-hp-2
u_height: 1
is_full_depth: false
weight: 9.6
weight_unit: kg
cf_ant_frequency: 80
cf_ant_diameter: 0.3
interfaces:
  - name: Waveguide
    type: other
    label: WG
  - name: Microwave Air
    type: other-wireless
    label: Microwave Air
```
