### DISCUSSION TITLE
How to use yaml files with complete info?

### DISCUSSION THREAD

**Discussion by ghost** [netbox-community/netbox#13952] [Q&A]
looking at the [devicetype-library](https://github.com/netbox-community/devicetype-library/tree/master) we can see that we can include port and modules by simply adding something like:
```
console-ports:
  - name: con 0
    type: rj-45
  - name: usb
    type: usb-mini-b
interfaces:
  - name: GigabitEthernet1/0/1
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
```

I tried doing the same for Site Contacts (same with circuit provider contacts).
like
```
  contacts:
    - name: someone's name
      role: Engineering
      priority: primary
```
but it does not seem to work, what am I missing here?
Is there an online document that we can reference?
