### DISCUSSION TITLE
Netbox - Redis issues

### DISCUSSION THREAD

**Discussion by stefanelul2000** [netbox-community/netbox#14350] [Help Wanted!]
I am not really using netbox that oftern but right now I have just realized that my instance is not working properly. has there been any recent changes to the container itself or redis ?

Below is the docker-compose I am using for deploying the container.
```
version: "3.8"
services:  
  postgresql:
    image: postgres:14
    hostname: ${DOCKERHOSTNAME}
    container_name: postgresql
    networks:
      - database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD = ${PGPASS}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:latest
    hostname: ${DOCKERHOSTNAME}
    container_name: redis
    networks:
      - backend
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDISPASS}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}       
    restart: unless-stopped
    volumes: 
      - ${DOCKERCONFDIR}/redis:/data
  netbox:
    image: lscr.io/linuxserver/netbox:latest
    hostname: ${DOCKERHOSTNAME}
    container_name: netbox
    networks:
      - backend
      - database
    ports:
      - 8088:8000  
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - SUPERUSER_EMAIL=admin@domain.com
      - SUPERUSER_PASSWORD=${NBPASS}
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=${NBDBPASS}
      - DB_HOST=postgresql
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDISPASS}
      - REDIS_DB_TASK=0
      - REDIS_DB_CACHE=1
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFDIR}/netbox:/config     
networks:
  database:
    external: true
  backend:
    external: true
```
