### DISCUSSION TITLE
Reverse accessor on Tags for plugins

### DISCUSSION THREAD

**Discussion by bkampsnl** [netbox-community/netbox#14466] [Help Wanted!]
Hi,

I'm trying to fix an issue in a conflict between the bgp and netbox-routing plugins.

Both plugins have a PrefixList class that derives from NetboxModel. Both classes are in their own namespace but there is a conflict in the tags (derived from NetboxModel>TagsMixin.

When I use both plugins I get the following error during database migration:

```
ERRORS:
netbox_bgp.PrefixList.tags: (fields.E304) Reverse accessor 'Tag.prefixlist_set' for 'netbox_bgp.PrefixList.tags' clashes with reverse accessor for 'netbox_routing.PrefixList.tags'.
        HINT: Add or change a related_name argument to the definition for 'netbox_bgp.PrefixList.tags' or 'netbox_routing.PrefixList.tags'.
netbox_routing.PrefixList.tags: (fields.E304) Reverse accessor 'Tag.prefixlist_set' for 'netbox_routing.PrefixList.tags' clashes with reverse accessor for 'netbox_bgp.PrefixList.tags'.
        HINT: Add or change a related_name argument to the definition for 'netbox_routing.PrefixList.tags' or 'netbox_bgp.PrefixList.tags'.
```

I'm trying to fix it but i'm not sure how. The related_name field should be changed so there is no clash. But is this issue in the base class TagsMixin?
