### DISCUSSION TITLE
Scripts are stuck at "running state" on execution

### DISCUSSION THREAD

**Discussion by Ariteme** [netbox-community/netbox#16298] [Help Wanted!]
I am currently trying to start creating scripts for netbox, but on every run job stuck at "running" state and never quits.
Here is the log from netbox-worker-docker:

08:57:32 default: extras.scripts.run_script(commit=False, data={}, job=<Job: 1aa8a2f4-30dc-4d71-b6b2-e6b864181efb>, request=<utilities.request.NetBoxFakeRequest object at 0x7f1716bb1950>) (1aa8a2f4-30dc-4d71-b6b2-e6b864181efb)
08:57:32 [Job 1aa8a2f4-30dc-4d71-b6b2-e6b864181efb]: exception raised while executing (extras.scripts.run_script)
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/worker.py", line 1430, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1280, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1317, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/extras/scripts.py", line 627, in run_script
    script = ScriptModel.objects.get(pk=job.object_id).python_class()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

P.S. Just to mention that it just does not run me everything under Class, but is able to run regular python command. For example I'm able to do ping via script, but it shouldn't be under "run()" function to be executed.

Kindly asking for assist.

**Comment by candlerb** [comment]
Netbox version? Can you show the script?

I suggest you start with a simple "hello world" type of script, make sure you can run it, and then this would prove that the issue is with your script.

There are some sample scripts [here](https://github.com/netbox-community/customizations/tree/master/scripts), although many may not have been updated for Netbox 4.0.

**Comment by Ariteme** [comment]
8e461e56f6e1 (v4.0.2)
I tried example from the list you provided: add_device_type_components.py. It has the same issue.
In additional here is my script you asked for:

```
#!/opt/netbox/venv/bin/python
import django, os, sys
sys.path.append('/opt/netbox/netbox')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'netbox.settings')
django.setup()

import logging
from extras.scripts import Script
import subprocess

# Configure logging
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('/opt/netbox/netbox/scripts/ping_device.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class PingDevice(Script):
    class Meta:
        name = "Ping Device"
        description = "Ping a device with IP 10.60.60.17"
        default_commit = False
        logger.info("Logger before RUN")

    def run(self):
        ip_address = "10.60.60.17"
        logger.info(f"Starting ping to {ip_address}")

        try:
            # Use the ping command
            result = subprocess.run(
                ["ping", "-c", "4", ip_address],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                timeout=60  # Add a timeout (in seconds) to prevent the script from hanging indefinitely
            )

            if result.returncode == 0:
                logger.info(f"Ping to {ip_address} successful:\n{result.stdout}")
                self.log_success(f"Ping to {ip_address} successful:\n{result.stdout}")
            else:
                logger.error(f"Ping to {ip_address} failed:\n{result.stderr}")
                self.log_failure(f"Ping to {ip_address} failed:\n{result.stderr}")

        except subprocess.TimeoutExpired:
            logger.error(f"Ping to {ip_address} timed out")
            self.log_failure(f"Ping to {ip_address} timed out")

        except Exception as e:
            logger.error(f"An error occurred: {e}")
            self.log_failure(f"An error occurred: {e}")
logger.info("Logger after RUN")
```

Here is the docker stack:
NAMES
docker-netbox-worker-1
docker-netbox-housekeeping-1
docker-netbox-1
docker-redis-1
docker-postgres-1
docker-redis-cache-1

The container that the script appear in after adding via GUI is docker-netbox-1.
The one that is throwing me an error mentioned before is docker-netbox-worker-1.
From other thread  I understood that there might be an issue with the django that can't find a file referenced, but I am not sure how exactly script was initialized if I run it via GUI Customization>Scripts. 




UPD:
Tried hello world

```
from extras.scripts import Script


class AddDeviceTypeComponents(Script):
    class Meta:
        name = "Hello world!"
        description = "Hello world!"

    def run(self, data, commit):
        print("Hello world!")
```

Having the same issue with the worker.

**Reply by candlerb** [reply]
(Please can you edit your post and put three backticks (` ``` `) on a line of their own, before and after each code block, so it formats correctly - indentation is important for Python code)

How did you upload the script?

I just created a local file called `hello.py` on my laptop with the following contents:

```
from extras.scripts import Script

class Hello(Script):
    class Meta:
        name = "Hello world!"
        description = "Hello world!"

    def run(self, data, commit):
        self.log_success("Hello world!")
```

On a test Netbox 4.0.3 instance I then went to Customization > Scripts > Add, clicked Choose File, selected the file, then Create.

Now I see it in the list, with a "run script" button, and it works:

![image](https://github.com/netbox-community/netbox/assets/44789/fc543d74-a323-437b-bb36-23442a8cb4d1)

I can also run it like this:

```
# /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py runscript hello.Hello
[2024-05-27 13:22:11,645][INFO] - Running script (commit=False)
[2024-05-27 13:22:11,646][INFO] - Hello world!
[2024-05-27 13:22:11,646][INFO] - Database changes have been reverted automatically.
[2024-05-27 13:22:11,659][INFO] - Script completed in 0 minutes, 0.02 seconds
```

BEWARE: Netbox keeps a database of the scripts and the classes, and if you change a script class by editing the python file directly sometimes it doesn't notice the change. Better to delete the script from the web UI, and re-upload it.

```
netbox4=# select * from extras_script;
 id | name  | module_id | is_executable
----+-------+-----------+---------------
  1 | Hello |        34 | t
(1 row)
```

Aside: this is a machine that I updated from 3.7 to 4.0. Although there are other scripts in the directory, and they are shown in the script listing, there are no 'Run script' buttons next to them. Possibly the script files need changing, or possibly I need to re-upload them to get them into the database. I've not gotten around to debugging this yet.

EDIT: I had done the database migration *before* copying the scripts back into the scripts directory on the new VM. It seems that to fix the problem I have to:
* download the file
* delete it from the web UI
* re-upload it from the web UI

**Reply by Ariteme** [reply]
I edited my comment above to better visibility.
Tried the code you suggested, it still doesn't run it to me.

Here are the screenshot of the flow:
1. Uploading your suggested code via webGUI
![image](https://github.com/netbox-community/netbox/assets/25263025/dc585028-77f1-4dc2-ba99-aab2b0c36bb2)
 It stored me the file in container "docker-netbox-1" in path "/opt/netbox/netbox/scripts/example_netbox.py"
in container "docker-netbox-worker-1" there is no such file.
Then I run the script by "Run Script" button in WebGUI.
It stuck in "running state"
![image](https://github.com/netbox-community/netbox/assets/25263025/f450b362-5470-40d2-aa32-9716ba45aa88)
and the only strange log I receive on my cluster is from container "docker-netbox-worker-1" where we can see the error mentioned above. Here is the screenshot: 
![image](https://github.com/netbox-community/netbox/assets/25263025/c82a9349-43e6-45c5-a78d-f1afded555a4)

Seems like it does not matter which netbox script it runs it just stuck on it with the python error.

**Reply by candlerb** [reply]
Then there's something different between your system and mine. I'm running Netbox standalone (without docker) which is one possible difference.

**Reply by candlerb** [reply]
Additional info: while re-uploading my existing scripts, I was able to replicate a problem similar to yours when *deleting* an existing script:

![image](https://github.com/netbox-community/netbox/assets/44789/88b7d2d1-ecb3-419c-b7f4-4c4b0235b0e9)

![image](https://github.com/netbox-community/netbox/assets/44789/b84e4a0d-c075-4e70-aa25-8df719533e55)

This is weird. The script has been deleted from the filesystem, but remains in the database:

```
netbox4=# select id,file_root,file_path from core_managedfile where file_path like '%showdata%';
 id | file_root |  file_path
----+-----------+-------------
 32 | scripts   | showdata.py
(1 row)
```

(Aside: historically, Netbox has been very poor about dealing with scripts that have problems in them, which makes them very hard to develop. It's not just you or me)

It turns out that trying to delete the event rule by itself gave the same exception.

I had to delete the eventrule by hand using SQL:

```
netbox4=# delete from extras_eventrule where name='test-showdata';
ERROR:  update or delete on table "extras_eventrule" violates foreign key constraint "extras_eventrule_con_eventrule_id_c177fa54_fk_extras_ev" on table "extras_eventrule_object_types"
DETAIL:  Key (id)=(2) is still referenced from table "extras_eventrule_object_types".
netbox4=# delete from extras_eventrule_object_types where eventrule_id=2;
DELETE 1
netbox4=# delete from extras_eventrule where name='test-showdata';
DELETE 1
```

**Reply by Ariteme** [reply]
Yeah, I am deleting the scripts via GUI without any problem. 
The problem occurs when I am trying to run any of it.

**Reply by jirivrany** [reply]
Hello, I had similar issue. The problem was in configuration of docker volumes and their mapping into the netbox and netbox-worker containers. 
What you can try:
1. check your config.py if there is SCRIPTS_ROOT set. If so, be sure to map your volumes to this. Or disable this directive, and keep it on default /opt/netbox/netbox/scripts
2. check your docker-compose.yml and create your scripts dirs as the volumes are described:
```
 volumes:
    - ./configuration:/etc/netbox/config:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:rw
    - netbox-reports-files:/opt/netbox/netbox/reports:rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
```
3. if you changing the volumes in docker-compose-override.yml be sure, that you map the scripts to the netbox-worker too. This was my solution. I'm using override a lot, because I need to work on  plugiin development localy. So here is my complete override file:
```
x-netbox-common: &common
    image: netbox:407-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    restart: unless-stopped
    user: "0:0" # root user, without it setup.py develop will not work
    tty: true
    env_file:
      - env/netbox.env
      

services:
  netbox:
    <<: *common
    container_name: netbox
    command: >
      sh -c "/opt/netbox/venv/bin/pip install -e /opt/netbox/netbox/netbox_cesnet_services_plugin/ &&
      /opt/netbox/venv/bin/python manage.py makemigrations &&
      /opt/netbox/venv/bin/python manage.py migrate &&
      /opt/netbox/venv/bin/python manage.py runserver 0.0.0.0:8080"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=supersecretpassword
    ports:
      - 8000:8080
    volumes:
      - ./configuration-plugin:/etc/netbox/config:z,ro
      - ./reports:/opt/netbox/netbox/reports:rw
      - ./scripts:/opt/netbox/netbox/scripts:rw
      - ./plugins/my-first-plugin:/opt/netbox/netbox/my-first-plugin
      - ./plugins/netbox_cesnet_services_plugin:/opt/netbox/netbox/netbox_cesnet_services_plugin  
      

  netbox-worker:
    <<: *common
    container_name: netbox-worker
    volumes:
      - ./configuration:/etc/netbox/config:z,ro
      - ./reports:/opt/netbox/netbox/reports:rw
      - ./scripts:/opt/netbox/netbox/scripts:rw
      
  netbox-housekeeping:
    <<: *common
    container_name: netbox-housekeeping
    volumes:
      - ./configuration:/etc/netbox/config:z,ro
      - ./reports:/opt/netbox/netbox/reports:rw
      - ./scripts:/opt/netbox/netbox/scripts:rw
      
```
