### DISCUSSION TITLE
OpenIdConnectAuth <class 'TypeError'>, not sure what's actually wrong.

### DISCUSSION THREAD

**Discussion by silmarine** [netbox-community/netbox#17121] [Help Wanted!] [answered]
I get an error when I try to login with openid:
```
<class 'TypeError'>

unsupported operand type(s) for +: 'NoneType' and 'str'
```
![image](https://github.com/user-attachments/assets/01df9651-b1a3-4dce-9e5a-05cc434eefd5)

I am trying to get it to work with Authelia but I cannot find any example configs for it with Netbox and am having to figure it out on my own. Because of that I assume I've made an error in the config somewhere. But this error doesn't tell me anything that helps. Anyone have any ideas?

**Comment by candlerb** [comment]
Perhaps you could start by showing your config?  You can find sample configs for keycloak and vault in the discussion archives.

**Reply by silmarine** [reply]
sorry, didn't mean to be lacking in info. This error just didn't have anything to go off of and I wasn't sure if it actually was a config issue or what. anyways, yes I used a lot of keycloak and authentik guides to help. I am also not unfamiliar with python so I looked though the OpenIdConnectAuth section.

I'm using the linuxserver docker image, here is my compose file netbox section:

```
  netbox:
    image: lscr.io/linuxserver/netbox:latest
    container_name: netbox
    restart: unless-stopped
    depends_on:
      - postgres
      - netbox-redis
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=996
      - TZ=Europe/Berlin
      - ALLOWED_HOST=netbox.mydomain.tld
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=<secret>
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=netbox-redis
      - REDIS_PORT=6379
      - REDIS_DB_TASK=0
      - REDIS_DB_CACHE=1
      - REMOTE_AUTH_ENABLED=True
      - REMOTE_AUTH_BACKEND=social_core.backends.open_id_connect.OpenIdConnectAuth
      - REMOTE_AUTH_AUTO_CREATE_USER=True
      - SOCIAL_AUTH_OIDC_OIDC_ENDPOINT=https://auth.mydomain.tld
      - SOCIAL_AUTH_OIDC_ID_KEY=netbox
      - SOCIAL_AUTH_OIDC_SECRET=<secret>
      - SOCIAL_AUTH_OIDC_SCOPE=['groups']
      - LOGOUT_REDIRECT_URL=https://auth.mydomain.tld/logout
    volumes:
      - /opt/docker/netbox:/config
```
and here is my Authelia client config for netbox:
```
    - client_id: 'netbox'
      client_name: 'Netbox'
      client_secret: <secret>
      public: false
      authorization_policy: 'two_service'
      consent_mode: 'implicit'
      redirect_uris:
        - 'https://netbox.mydomain.tld/login'
      scopes:
        - 'openid'
        - 'email'
        - 'profile'
        - 'groups'
      userinfo_signed_response_alg: 'RS256'
```
I have not made any changes to the configuriation.py file.

**Reply by candlerb** [reply, marked as answer]
I don't know anything about Authelia, but:

1. I'm not 100% sure you can use `social_core.backends.open_id_connect.OpenIdConnectAuth` directly without subclassing it. A while back, I tried to contribute this feature rather than a custom Vault subclass. Full gory history in https://github.com/python-social-auth/social-core/pull/669 but some of it (the group membership part) was reverted in https://github.com/python-social-auth/social-core/pull/692

2. Even if that were to work, I think you've got the wrong redirect_uris:

```
      redirect_uris:
        - 'https://netbox.mydomain.tld/login'
```

should be

```
      redirect_uris:
        - 'https://netbox.mydomain.tld/oauth/complete/oidc'   # See "name = 'oidc'" in PSA source
```

But having said that, I'd expect Authelia to complain that it's asking to be redirected to a uri which is not in the permitted list, and it should be pretty clear what the correct one is. It sounds like it's not getting that far.

Aside: if you want to make use of groups, I believe you also have to hack the auth pipeline; you can find info on this in past discussions. Personally I abandoned PSA and went back to Apache mod_auth_openidc.

As for the `NoneType + str` error, you need to get a full backtrace from Netbox. Either set DEBUG=True, or set ADMINS and EMAIL to get all exceptions mailed out to you. I don't run Netbox in Docker so I don't know if those are available as environment variables or you have to set them in [extra.py](https://github.com/netbox-community/netbox-docker/wiki/Configuration#custom-configuration-files)

**Reply by silmarine** [reply]
Ah okay, that is all much too complicated to be worth it for my little home lab. I think I will just abandon using openid all together and just create local accounts. At least for now until it get better out of the box support, if it ever does. Thanks for the help!

**Comment by mongrelion** [comment]
I ran into the same issue that you are having. I'm also using docker compose.
The problem is that you would think that the ` SOCIAL_AUTH_` environment variables would be automatically consumed and passed on to `social_core` but that is actually not the case.

You have to initialize those variables in your `configuration.py` *as well*:

```python
SOCIAL_AUTH_OIDC_OIDC_ENDPOINT=environ.get('SOCIAL_AUTH_OIDC_OIDC_ENDPOINT')
SOCIAL_AUTH_OIDC_ID_KEY=environ.get('SOCIAL_AUTH_OIDC_ID_KEY')
SOCIAL_AUTH_OIDC_SECRET=environ.get('SOCIAL_AUTH_OIDC_SECRET')
SOCIAL_AUTH_OIDC_SCOPE=environ.get('SOCIAL_AUTH_OIDC_SCOPE')
```

After doing that, I was able to get it off the ground!

Good luck.

**Reply by silmarine** [reply]
I tried that but get a python3 error for those lines:
```
netbox  | 2025-01-07T11:03:42.205476393Z   File "/app/netbox/netbox/netbox/configuration.py", line 249, in <module>
netbox  | 2025-01-07T11:03:42.205580130Z     SOCIAL_AUTH_OIDC_OIDC_ENDPOINT=environ.get('SOCIAL_AUTH_OIDC_OIDC_ENDPOINT')
netbox  | 2025-01-07T11:03:42.205589236Z                                    ^^^^^^^
netbox  | 2025-01-07T11:03:42.205637180Z NameError: name 'environ' is not defined
netbox  | 2025-01-07T11:03:42.786977085Z daemon "python3 ./manage.py rqworker" (pid: 191) annihilated
```
Did you do anything to define 'environ'?

**Reply by mongrelion** [reply]
I didn't. It was already defined in my file. But you can just import it at the top of your file:

```python
from os import environ
```

**Comment by sub2010** [comment]
I am trying to integrate NetBox (v4.4.1 in Docker) with Keycloak (OIDC) for authentication.
NetBox is running behind pfSense HAProxy with TLS termination.

When I try to log in via Keycloak (/oauth/login/keycloak/), I always get:

```
500 Internal Server Error
<class 'TypeError'>
Cannot mix str and non-str arguments
```


Docker Compose
```
services:
  postgres:
    image: postgres:15
    container_name: netbox-postgres
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: netbox-redis
    restart: unless-stopped

  netbox:
    image: netboxcommunity/netbox:latest
    container_name: netbox
    depends_on:
      - postgres
      - redis
    environment:
      TZ: "Europe/Berlin"
      SECRET_KEY: "<RANDOM_SECRET>"
    
      # Datenbank
      DB_NAME: "netbox"
      DB_USER: "netbox"
      DB_PASSWORD: "<DB_PASSWORD>"
      DB_HOST: "postgres"
      DB_WAIT_TIMEOUT: "60"
    
      # Redis
      REDIS_HOST: "redis"
    
      # Proxy / Security
      ALLOWED_HOSTS: "netbox.example.com"
      USE_X_FORWARDED_HOST: "true"
      SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
      CSRF_TRUSTED_ORIGINS: "https://netbox.example.com"
    
      # Login
      LOGIN_REQUIRED: "true"
    
      # Keycloak (OpenID Connect)
      REMOTE_AUTH_BACKEND: "social_core.backends.keycloak.KeycloakOAuth2"
      SOCIAL_AUTH_KEYCLOAK_KEY: "netbox"
      SOCIAL_AUTH_KEYCLOAK_SECRET: "<CLIENT_SECRET>"
      SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: "https://sso.example.com/realms/<REALM>/protocol/openid-connect/auth"
      SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: "https://sso.example.com/realms/<REALM>/protocol/openid-connect/token"
      SOCIAL_AUTH_KEYCLOAK_USER_INFO_URL: "https://sso.example.com/realms/<REALM>/protocol/openid-connect/userinfo"
      SOCIAL_AUTH_KEYCLOAK_ID_KEY: "preferred_username"
      SOCIAL_AUTH_REDIRECT_IS_HTTPS: "true"
      SOCIAL_AUTH_LOGIN_REDIRECT_URL: "/"

```
Pfsense HA Proxy Konfig

``` 
frontend netbox_frontend
    bind 192.168.X.254:443 ssl crt-list /var/etc/haproxy/shared-http-s.crt_list
    bind 192.168.X.254:80
    mode http
    log global

    # HTTPS erzwingen
    acl https ssl_fc
    http-request redirect scheme https unless https

    # Forwarded-Header setzen (wichtig für Django/NetBox)
    http-request set-header X-Forwarded-Proto https if https
    http-request set-header X-Forwarded-Port 443
    http-request set-header X-Forwarded-Host %[req.hdr(Host)]

    # Host-Matching für NetBox
    acl host_netbox hdr(host) -i netbox.example.com
    use_backend netbox_backend if host_netbox

    default_backend status_backend
    backend netbox_backend
    mode http
    option forwardfor
    option http-keep-alive
    timeout connect 30s
    timeout server 30s
    server netbox 192.168.X.230:8001 check
```
Keycloak Config

```
{
  "clientId": "netbox",
  "name": "NetBox",
  "enabled": true,
  "protocol": "openid-connect",
  "publicClient": false,
  "clientAuthenticatorType": "client-secret",
  "secret": "<CLIENT_SECRET>",
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": false,
  "serviceAccountsEnabled": false,
  "frontchannelLogout": true,
  "redirectUris": [
    "https://netbox.example.com/complete/keycloak/"
  ],
  "webOrigins": [
    "https://netbox.example.com"
  ],
  "attributes": {
    "use.jwks.url": "true"
  },
  "defaultClientScopes": [
    "web-origins",
    "roles",
    "profile",
    "email"
  ],
  "optionalClientScopes": [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt"
  ]
}


```
