### DISCUSSION TITLE
Local Datasource No Data files found

### DISCUSSION THREAD

**Discussion by aascedu** [netbox-community/netbox#17633] [Q&A]
Hello.

I am using Netbox 4.1.1 deployed with netbox-docker.
I want to add a local datasource as a way to load router config files through a volume.
The files I want to import to my Netbox instance are where they are supposed to be ( in `/opt/netbox/netbox/datasource`) but the local datasource cannot find the files when syncing...

Here is `/opt/netbox/netbox` folder, we can see datasource and some other folder which are part of netbox :
![image](https://github.com/user-attachments/assets/94778286-c3bb-4f98-a09c-c607deff63f3)

The folder is populated with my files :
![image](https://github.com/user-attachments/assets/731c9958-ebf4-477c-aa1c-2555d12c42c1)

Here is the files I get when I use `/opt/netbox/netbox` as a URL (we can see files from some folder) : 
![image](https://github.com/user-attachments/assets/d40d425f-9bd7-4980-adae-59ad64486999)

However when I set the URL to `/opt/netbox/netbox/datasource`, **NOTHING** : 
![image](https://github.com/user-attachments/assets/90ea78c5-2a0e-4cdb-8f6d-4c2604c25de1)

I don't understand why it doesn't work... I tried creating my own folder inside the docker container of netbox, in `/opt/netbox/netbox` called `test` and same as with datasource, it didn't work. I tried changing the folder properties with chown but nothing works.

**_Note :_** I tried to add `/etc/netbox` as a Local datasource, which worked : 
![image](https://github.com/user-attachments/assets/4a2dd177-663a-4d71-998a-280deddd4736)

but here is what's inside `/etc/netbox` :
![image](https://github.com/user-attachments/assets/322e8b9a-c653-4963-aa0d-76472d1f1df1)

It just doesn't make any sense since my config folder is a Docker volume as well... even if I try to create a folder inside the container at `/etc/netbox/test`, put a file in there, the Datasource doesn't detect it...

Update : it is not about folder but rather about files. I copied one of the files that were in the datasource into a folder I could manage to get synced correctly, and it doesn't show... They have the same group and owner, same rwx properties but my file originating from my docker volume just doesn't show which is **_SUPER WEIRD_** since when trying with another Docker Volume (in Read-Only mode), the files appears...

Am I missing something or is there something I could do to make that work ?
Thank you.

**Comment by an-ky** [comment]
I was searching around for a solution the better part of the day and it looks like I got one. The syncing process is done by a rqworker running in the netbox-worker container so it needs to see the volume, too.

With the following `docker-compose.override.yaml`  I'm able to set an arbitrary directory as data source:

```
version: '4.1.7'
services:
  netbox: 
    ports:
    - 8000:8080
    environment:
      [...]
    volumes:
      - ./templates:/datasource:rw
  netbox-worker:
    volumes:
      - ./templates:/datasource:rw
```
This uses a host directory which needs to have the proper access right set. 

With a named volume I had to apply a ~hack~ workaround using an init container to set proper permission. Without the init container the volume will be mounted as root:root 755 which isn't sufficient for netbox which runs as `unit`. I haven't found how the netbox compose file or container init scripts change the permissions for /opt/netbox/netbox/scripts and reports respectively, which are also mounted named volumes (according to docker-compose.yaml).

```
version: '4.1.7'
services:
  init-volume:
    image: ubuntu
    user: root
    volumes:
      - templates:/tmp/templates
    command: ["/bin/bash", "-c", "chown 999:0 /tmp/templates && chmod 775 /tmp/templates"]
  netbox: 
    user: "unit:root"
    ports:
    - 8000:8080
    environment:
      [...]
    volumes:
      - templates:/datasource:rw
    depends_on: &dep-init
      init-volume:
        condition: service_completed_successfully
  netbox-worker:
    user: "unit:root"
    volumes:
      - templates:/datasource:rw
    depends_on:
      <<: *dep-init
 
volumes:
  templates:
    driver: local
```

Hope that helps
