### DISCUSSION TITLE
How to run a custom rqworker automatically everytime the netbox container being started

### DISCUSSION THREAD

**Discussion by ArmansPing** [netbox-community/netbox#18293] [Help Wanted!]
Netbox only runs three default rqworkers named "default" "high" "low".

How to run a custom rqworker automatically everytime the netbox container being started?

**Comment by candlerb** [comment]
If you are running netbox locally using systemd, this is controlled by [netbox-rq.service](https://github.com/netbox-community/netbox/blob/v4.1.10/contrib/netbox-rq.service#L14). It runs a single rqworker listening on those three queues:

```
ExecStart=/opt/netbox/venv/bin/python3 /opt/netbox/netbox/manage.py rqworker high default low
```

But you say "container". Are you running via docker-compose? In that case, the arguments to rqworker are configured in [docker-compose.yml](https://github.com/netbox-community/netbox-docker/blob/3.0.2/docker-compose.yml#L25-L28)

Again, this only runs a single rqworker. The supplied docker-compose file doesn't provide any queue names, so the [DEFAULT_QUEUES](https://github.com/netbox-community/netbox/blob/v4.1.10/netbox/core/management/commands/rqworker.py#L6) setting is used (which is also "high", "default", "low"). But you should be able to add the extra arguments yourself:

```
  netbox-worker:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
      - high
      - default
      - low
      - my_custom_queue
```

If you wanted to run more than one rqworker process then you'd configure additional containers in docker-compose.yml.
