### DISCUSSION TITLE
Why doesn't the Cable creation API support matching on objects like other parts of the API?

### DISCUSSION THREAD

**Discussion by deliciouslytyped** [netbox-community/netbox#18648] [General]
Why doesn't the Cable creation API support matching on objects like other parts of the API?

Parts of the API allow specifying objects by specifying a subset of attributes resulting in a unique object (I don't know offhand which part of the docs this is stated in), but creating cable (terminations) requires specifying the termination object type (for example 'dcim.interface') and an object id.

For example (I have some custom yaml processing code that basically maps this to `pynetbox nb.dcim.devices.create(...)`):
```
Device:
  - name: JBOD-30
    slug: jbod-30
    role:
      slug: storage
    device_type:
      slug: somejbod
    site:
      slug: mysite
    rack:
       name: Rack 1
    face: front
    status: planned
```
Here `role`, `device_type`, `ite`, and `rack` match an appropriate object.

Creating cables doesn't seem to support this.

This makes user automation code more complicated and also requires doing a round-trip to first retrieve the IDs (which can also result in TOCTOU issues.)
