### DISCUSSION TITLE
Creating Module-bays importing Module-Types.

### DISCUSSION THREAD

**Discussion by segachan** [netbox-community/netbox#19184] [Ideas]
I suggest that Netbox allow to make the module-bays from importing `module-type` as the new feature. 
I know that manually adding the nested Module is supported at v4.2.6, thank you. This is the good feature.
It's better that user can automatically import from `module-types`.

The following behavior is in the current version:
1. Importing the module-type yaml at "Module Type Bulk Import" in "Module-types" tab.

![Image](https://github.com/user-attachments/assets/f85bba86-4061-448e-af74-3ab1b3961910)
Data:
```
---
manufacturer: Cisco
model: A9K-AC-PEM-V3
slug: A9K-AC-PEM-V3
part_number: A9K-AC-PEM-V3
module-bays:
  - name: 0/PT0
    label: 0/PT
    position: 0
    description: Simulated Power Tray IDPROM
  - name: 0/PT1
    label: 0/PT
    position: 1
    description: Simulated Power Tray IDPROM
  - name: 0/PT2
    label: 0/PT
    position: 2
    description: Simulated Power Tray IDPROM
  - name: 0/PT3
    label: 0/PT
    position: 3
    description: Simulated Power Tray IDPROM
```
`module-type` is collectly imported:
![Image](https://github.com/user-attachments/assets/ea6d04cc-3bfd-4336-ad77-0fb409ecdd58)

Adding a module on a device, using `A9K-AC-PEM-V3` which is just now made:
![スクリーンショット 2025-04-15 8 32 21](https://github.com/user-attachments/assets/50de7517-f334-4b23-b732-bc911e94d43b)
![スクリーンショット 2025-04-15 8 35 03](https://github.com/user-attachments/assets/3eb006e0-0066-48a0-84d9-87f80911f4d5)

The below is that expecting the behavior:
---
The below is that expecting the behavior:
When I create the module instance, which has the module-bays and defined as the module-types, the `module-bays` automatically also created.  For example, when just now made `A9K-AC-PEM-V3` module is instanced, the more four `module-bays` named `0/PT0` `0/PT1` `0/PT2` `0/PT3` is created under a `module-bay` named `Power Bay 0` .
![image](https://github.com/user-attachments/assets/428c89c5-0a37-4bd9-a11b-184ab1e2c9ea)
---

refference issue:
https://github.com/netbox-community/netbox/issues/10500

Version:
v.4.2.6
