### DISCUSSION TITLE
[Netbox Helm chart Kubernetes] Redis configuration not applied -  connecting to localhost:6379. Connection refused. -> External redis

### DISCUSSION THREAD

**Discussion by MacherelR** [netbox-community/netbox#19341] [General]
Hi, 

I'm currently trying to deploy Netbox on my kubernetes cluster using the helm chart. 
I'd like to use external separate postgresql and redis instances. To do so, I included them in my chart's dependencies:
```
dependencies:
  - name: redis
    alias: redis1
    repository: file://../redis
    version: 20.11.5
  - name: postgresql
    alias: postgresql
    repository: file://../postgresql
    version: 16.6.3
    condition: postgresql.enabled
```

Now I followed the documentation of Netbox's helm chart saying if you got an external redis instance you need to defined enabled = false under the `redis` key.
So I did the following:
```
redis:
  enabled: true
  
redis1:
  global:
    imageRegistry: <some_registry>
  architecture: "standalone"
  persistence:
    size: 2Gi
    storageClass: ""
  auth:
    enabled: false
  networkPolicy:
    enabled: false
    
tasksRedis:
  database: 0
  ssl: false
  host: <redis_master_svc_name>
  port: 6379
  insecureSkipTlsVerify: true

cachingRedis:
  database: 1
  ssl: false
  host: <redis_master_svc_name>
  port: 6379
  insecureSkipTlsVerify: true
```

And deployed everything. Redis seems to be deployed just fine but when I trying reaching the Netbox page, I get the error :
`Error 111 connecting to localhost:6379. Connection refused.`, error that also happens at some point in the netbox pod start.

Thing is, I can't find what was wrongly defined as the configuration doesn't seem to be correctly applied to netbox and it still uses the default `localhost` one to reach redis...

By going exec into the netbox pod and printing its env variable I can see for example:
`NETBOX_REDIS1_MASTER_SERVICE_HOST=<Service_IP>` which I guess means the config is still transfered somewhere...

Anyone can help ?
