### DISCUSSION TITLE
Mirroring data between two netboxes

### DISCUSSION THREAD

**Discussion by SchmidtJonathan1** [netbox-community/netbox#19786] [Q&A]
Hi, I'm wondering what the best way is to mirror data between two separate netboxes. My idea was to use events and automation to achieve a mirroring. Instead of always importing a backup from one to the other. 
There can be different data in the netboxes and only some of it is the same.
Has anyone had any experience with this?
Many thanks for your help.

**Comment by wols** [comment]
The [DebOps](https://docs.debops.org/) project contains an Ansible [Role](https://docs.debops.org/en/stable-3.2/ansible/roles/netbox/) for a **primary/standby configuration**.

[Quote](https://docs.debops.org/en/stable-3.2/ansible/roles/netbox/defaults/main.html#primary-standby-configuration):

> `netbox__primary`
> Boolean to define if the instance of NetBox will be primary or not. True: This instance will become primary and needs read and write database access. False: This instance will become standby, "netbox__config_maintenance_mode" will be set to True and "netbox__config_session_file_path" will be populated.

Note: This requires/recommends managing the Redis/**Postgresql cluster**/Netbox servers with DebOps. Not a bad idea - in my opinion.

**Comment by SchmidtJonathan1** [comment]
Thanks we found a solution with ansible

**Reply by wols** [reply]
Can you share the playbook? That would be cool.

**Reply by SchmidtJonathan1** [reply]
I haven't forgotten you. I will share the code later.

**Reply by SchmidtJonathan1** [reply]
Hello, here is the code. The logic and development are not mine, but from colleagues. Here is a rough outline of what the playbook does. If you want to export more things, you can create additional role task files based on nb_sites.yml. A Python script is also used for the virtual clients. I hope it helps to start with a solution.

```
---
# vars
netbox_url_first: ""
netbox_token_first: ""
netbox_url_second: ""
netbox_token_second: ""
object_types:
  - sites
required_keys_sites:
  name: name
  slug: slug
  group: group
  region: region

---
# site.yml
- name: Sync data between two netboxes
  hosts: localhost
  gather_facts: false
  roles:
    - role: sync_data

---
# role main.yml
- name: Import task
  ansible.builtin.import_tasks: get_data.yml
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url_first }}"
      netbox_token: "{{ netbox_token_first }}"

- name: Copy data to second netbox
  ansible.builtin.import_tasks: nb_sites.yml
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url_second }}"
      netbox_token: "{{ netbox_token_second }}"
---
# get_data.yml
- name: Get data for each object
  ansible.builtin.set_fact:
    desired_{{ item }}: "{{ current_object_data | map(attribute='value') | ansible.builtin.json_query('[].' + vars['required_keys_' + item] | to_json) }}"
  loop: "{{ object_types }}"
  vars:
    current_object_data: "{{ query('netbox.netbox.nb_lookup', item | replace('_', '-'), api_endpoint=netbox_url, token=netbox_token) }}"

- name: Output file
  ansible.builtin.copy:
    content: "{{ {'desired_' + item: vars['desired_' + item]} | to_nice_yaml(indent=2, explicit_start=true) }}"
    dest: "{{ role_path }}/files/main/{{ item }}.yml"
    mode: "0740"
  # become: true
  loop: "{{ object_types }}"

- name: Reload var file
  ansible.builtin.include_vars:
    dir: "{{ role_path }}/files/main/"

---
# Role nb_sites.yml
- name: Create site
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url_second }}"
    netbox_token: "{{ netbox_token_second }}"
    data:
      name: "{{ item['name'] }}"
      slug: "{{ item['slug'] }}"
      region: "{{ item['region']['name'] }}"
      site_group: "{{ item['group']['name'] }}"
    state: present
  loop: "{{ desired_sites }}"
```
