### DISCUSSION TITLE
Netbox fails to connect to read-only postgresql

### DISCUSSION THREAD

**Discussion by fumped** [netbox-community/netbox#19857] [Help Wanted!]
### Deployment Type

Self-hosted

### NetBox Version

v4.3.1

### Python Version

3.10

### Steps to Reproduce

Netbox is supposed to be able to run towards read only replicas of Postgres. 
https://github.com/netbox-community/netbox/pull/12490
https://github.com/netbox-community/netbox/issues/11233

It fails to start.

We're running the official helm-chart but after input from Benjamin Reed it seems like the issue is in core netbox and not specific to the containerized version.

We have two completely separate kubernetes klusters in different countries. Lets call the main country C1 and the other site C2.

![Image](https://github.com/user-attachments/assets/783b0042-64d5-4d3b-b1eb-5f655998c852)

Netbox and the workers + Redis lives in kubernetes as containers and the Postgres databases are installed on RHEL machines.
C1 has 2 DBs, one Primary RW and one Replica in RO. C2 Just has a Replica in RO.

The idea is to have C1 running all the time and have C2 read-only towards the replica. In a DR scenario we can promote the RO replicas to RW.

C1 is up and running and is initialized. I want C2 to launch towards the same, populated databases.
So Yes, the Database is set to the Replica in C2 and to the VIP in C1.

Values:

# Chart netbox C1
```
netbox:
  externalDatabase:
    host: IP-FOR-C1-VIP
    port: 5432
    database: netbox
```
    
# Chart netbox C2
```
netbox:
  externalDatabase:
    host: IP-FOR-C2-IP
    port: 5432
    database: netbox    
```

### Expected Behavior

Netbox should successfully launch.

### Observed Behavior

```
"django.db.utils.OperationalError: connection failed: connection to server at "ip-address-here", port 5432 failed: session is read-only
[ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
:hourglass_flowing_sand: Waiting on DB... (3s / 30s)"
```

**Comment by arthanson** [comment]
@fumped Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

Can you please add repro steps, you don't put anything there about how you are configuring anything - are you setting DATABASES to something or?

**Comment by fumped** [comment]
Hi,

We have two completely separate kubernetes klusters in different countries. Lets call the main country C1 and the other site C2.


![Image](https://github.com/user-attachments/assets/842cd18f-4a94-4d28-9929-bff394b2ae56)


Netbox and the workers + Redis lives in kubernetes as containers and the Postgres databases are installed on RHEL machines.
C1 has 2 DBs, one Primary RW and one Replica in RO. C2 Just has a Replica in RO.
 
The idea is to have C1 running all the time and have C2 read-only towards the replica. In a DR scenario we can promote the RO replicas to RW.


C1 is up and running and is initialized. I want C2 to launch towards the same, populated databases.
So Yes, the Database is set to the Replica in C2 and to the VIP in C1.

Values:

```
# Chart netbox C1
netbox:
  externalDatabase:
    host: IP-FOR-C1-VIP
    port: 5432
    database: netbox
    
# Chart netbox C2
netbox:
  externalDatabase:
    host: IP-FOR-C2-IP
    port: 5432
    database: netbox    
```

If this is not supported, please let me know :).
