### DISCUSSION TITLE
YAML Device Template items for port description and label.

### DISCUSSION THREAD

**Discussion by DenHayes** [netbox-community/netbox#6672] [Q&A] [answered]
Does the YAML import for device templates support a description and label item for front and rear ports?   I reviewed the devicetype-library read-me and schema definition and I don't think so, but want to confirm. 

A description and label can be added when creating the device components via the WebUI. It would be nice to see this added to the import templates if not.

**Comment by candlerb** [comment, marked as answer]
Did you try it? The following works for me:

```
manufacturer: Unknown
model: Packet Shooter 9000
slug: packet-shooter-9000
u_height: 1
front-ports:
  - name: F1
    type: 8p8c
    rear_port: R1
    rear_port_position: 1
    description: foo
    label: FP1
rear-ports:
  - name: R1
    type: 8p8c
    positions: 1
    description: bar
    label: RP1
```

After import:

![image](https://user-images.githubusercontent.com/44789/124380990-10454380-dcb8-11eb-858a-d7b83dcf5ee9.png)

![image](https://user-images.githubusercontent.com/44789/124381003-1d623280-dcb8-11eb-8aef-806fc8f10b28.png)

**Reply by DenHayes** [reply]
Yes, I did give it a try; here's a snippet of the yaml I tried. 

```
---
manufacturer: Adva Optical
model: 96CSM/2HU-#19600-#19125
slug: 96csm2hu
comment: 96 Channel DWDM passive filter
part_number: '1078708800-01'
u_height: 2
is_full_depth: false
interfaces:
  - name: I
    type: other
    mgmt_only: true
    description: 'Interconnect Port'
rear-ports:
  - name: N
    type: lc
    positions: 96
    description: 'Network Port'
front-ports:
  - name: C1
    type: lc
    rear_port: N
    rear_port_position: 1
    description: '1529.55 nm'
  - name: C2
    type: lc
    rear_port: N
    rear_port_position: 2
    description: '1529.94 nm'
  - name: C3
    type: lc
    rear_port: N
    rear_port_position: 3
    description: '1530.33 nm'
```

Here's what it looks like after imported:

![image](https://user-images.githubusercontent.com/22125585/124683605-66261100-de9b-11eb-8b53-fc1a8d276f13.png)
![image](https://user-images.githubusercontent.com/22125585/124683638-7807b400-de9b-11eb-9c41-b02e4cd0b301.png)


I'm running version 2.11.1 and I see 2.11.8 was just released.  I'll upgrade and try again.

Thanks for confirming it should work.
