### DISCUSSION TITLE
Automating the creating of interfaces in a virtual chassis

### DISCUSSION THREAD

**Discussion by richardjohnallsopp** [netbox-community/netbox#6952] [Q&A]
I'm wondering if anyone has any ideas or suggestions for automating the creation of interfaces for virtual chassis nodes in Netbox? I would love to be able to use jinja 2 or the nice UI `Gi1/0/[1-48]` feature, but as these aren't exposed via the API or ansible modules (to my knowledge) I've been using the following.

```
    # create interfaces on each virtual chassis node
    - name: Create interface on each node
      netbox.netbox.netbox_device_interface:
        netbox_url: "https://{{ deployment_type }}"
        netbox_token: "{{ netbox_key }}"
        data:
          device: "{{ item[0].switch }}"
          name: "Gi{{ item[0].switch.split('_')[1] }}/0/{{ item[1].interface }}"
          type: "1000Base-t"
        state: present
      with_nested:
        - "{{ switches }}"
        - "{{ interfaces }}"
      when: item[0].device_type == "C9300-48P-A" or item[0].device_type == "WS-C3850-48P"
      tags:
        - add_interfaces
```
This works fine, but it's really slow when you're doing a full stack of 8 or 9 switches.
