### DISCUSSION TITLE
How to model VLAN interfaces

### DISCUSSION THREAD

**Discussion by antong** [netbox-community/netbox#7454] [Q&A] [answered]
On many platforms, one can add interfaces for specific tagged VLANs on a real interface. For example on Linux, if there are tagged VLANs 13 and 14 on eth0, I can make eth0.13 and eth0.14 and assign IP addresses for these. (On BSD, it could be igb0 and igb0_vlan13 and igb0_vlan14.)

Is the right way then to add all the physical interfaces as device interfaces and specify the tagged vlans (13 and 14) and perhaps an untagged vlan, and then in addition make virtual interfaces named like eth0.13 (mode access, untagged vlan 13)? Would this eth0.13 have eth0 as parent interface?

**Comment by ThomasADavis** [comment]
The way we are doing it (in yaml, which we feed into netbox), so we can use it in ansible.  Yes, there is other data we pickup from the node like inventory of dimms, drives, gbics, motherboard, etc. etc. This is then combined into netbox so we can generate node configs

```
      - name: bond0
        type: Link Aggregation Group (LAG)
        mode: Tagged (All)
        mtu: 9216

      - name: ovirtmgmt
        mtu: 9000
        type: virtual
        parent: bond0
        mode: access
        untagged_vlan:
          name: ovirtmgmt
          site: crt
          vlan_group: omni
        address: 192.168.84.200/22
        tags:
          - primary
          - default

      - name: eno1
        type: 10GBASE-T (10GE)
        mtu: 9216
        lag: bond0
        remote:
          switch: sw-d8-r13-u37
          port: swp9
          lag: bond0
          cable:
            color: '0000ff' # blue
            type: cat6
      - name: eno2
        type: 10GBASE-T (10GE)
        mtu: 9216
        lag: bond0
        remote:
          switch: sw-d8-r13-u39
          port: swp9
          lag: bond0
          cable:
            color: '0000ff' # blue
            type: cat6
```

So that's two interfaces, bonded together.  The bond is what we set as the 'trunk', and then we define virtual interfaces with the untagged vlan attribute for the vlan they are hooked to on the bond0, and also point the virtual interface parent to the bond0.

Yes, you can use named interfaces instead of bond0.50 for example.


so simply:

- create a trunk interface.
- add a virtual interface, mode = access, untagged_vlan = vlan, set parent to trunk.
