### DISCUSSION TITLE
Netbox Ansible inventory, getting all L2 vlans for a site/device

### DISCUSSION THREAD

**Discussion by hyberdk** [netbox-community/netbox#7669] [Q&A]
HI all, 

Im trying out the netbox.nb_inventory module to extract device information/fact for our Cisco devices.

Im not quite sure how to get layer2 vlans out of netbox and into ansible. since the vlans are not directly associated with a device but with a sites instead I do not get the vlan info from netbox.

I obvoiusly get any layer3 interfaces that are SVI, but for any "layer2" vlans, I dont get anything.  Looking at the API URLs that are being fetched, it looks like ipam/vlans are not even considered.

So the question is: how do I get the layer2 vlans for a site and associate with the device via the site-name

Any takers?

Esben

**Comment by mtinberg** [comment]
How you model this is going to depend a bit on your topology, but if VLANs are a Site specific thing then associating the VLANs with a Site will allow you to query for all VLANs for a Site to then apply to the Devices when you template the config.   If tying VLANs to Sites isn't the right model for your topology then you may need to put the VLANs in VLAN Groups and tie the groups to a Regions or Site Groups, which are two ways to organize Sites, a Site can be associated with one Region and one Site Group, and those are hierarchical so you have two overlapping ways to organize.

Another way to do it is if you always have VLANs presented on access/tagged interfaces, and don't have trunking config for VLANs that do not exist on the device (eg. trunking is not not dynamic or 2-4095 or whatever) then you can query all the interfaces associated with a device and fetch all untagged_vlan and tagged_vlans records and use that as your list, so when a VLAN is added to an interface the template can automatically add the instance. 

Here is an ansible way to scrape all the vlans using nb_lookup

 ```yaml
    netbox_interfaces: "{{ query('netbox.netbox.nb_lookup', 'interfaces', api_filter=interface_api_filter, api_endpoint=netbox_api, token=netbox_token) | map(attribute='value') | list }}" 
    tagged_vlans: "{{ netbox_interfaces | selectattr('tagged_vlans') | map(attribute='tagged_vlans') | flatten }}"
    untagged_vlans: "{{ netbox_interfaces | selectattr('untagged_vlan') | map(attribute='untagged_vlan') | flatten }}"
    ansible_vlans: "{{ tagged_vlans + untagged_vlans }}"
    vlans: "{{ ansible_vlans | unique | sort(attribute='vid') }}"

```

**Reply by hyberdk** [reply]
damn, I guess my last reply I did not push send.. 

Thanks for the reply Mark (@mtinberg), each of my sites have a vlan group assigned to it. We do not span vlans across sites, so vlans are site specific.. 

I have tried to play a little with it and ended up with this, its not very elegant and its really slow looping though all vlans (~5600), I can see the CPU hitting 100%

My "test" yml file looks like this:

```
---
- name: Get VLANs from Netbox
  hosts: localhost
  tasks:
    - name: setting variable
      ansible.builtin.set_fact:
        cacheable: yes
        vlans:  "{{ query('netbox.netbox.nb_lookup', 'vlans',
                      api_endpoint='https://netbox.<snip>.net/',
                      token='b2f739d<snip>d812f9f',
                      validate_certs=False) }}"

- name: vlans test
  gather_facts: False
  hosts: all
  tasks:
    - name: print vlans
      set_fact:
        all_vlans: "{{ hostvars.localhost.ansible_facts.vlans }}"

    - name: print vlans
      debug:
        msg: "{{ item }}"
      loop: "{{ all_vlans }}"
      when:
      - item.value.site.slug == sites[0]
      - item.value.status.value == "active"
```

Im using the localhost to store the vlan fact, so I can retrieve it from all my network devices. 

Is this really the best way?

Esben

**Reply by mtinberg** [reply]
I tested this in my lab and it seemed fairly quick, note that this does run a separate API query from each worker in parallel, so making sure your --forks or serial: do not overwhelm the web server(s) or database connection limit, but each query should be fairly fast

```yaml
---
- name: test vlan getter
  hosts: device_roles_access
  connection: network_cli
  # snip out unrelated settings
  vars:
    vlan_api_filter: "status=active site={{ sites[0] }}"
    vlans: "{{ query('netbox.netbox.nb_lookup', 'vlans', api_filter=vlan_api_filter, api_endpoint=netbox_api, token=netbox_token) | map(attribute='value') | list }}"
  tasks:
    - name: provision vlan
      delegate_to: localhost
      template:
        dest: "/var/tmp/ansible/{{ inventory_hostname }}-vlans.conf"
        src: "vlans.j2"
```


On an unrelated note, I did not know that when: clauses could take a list to && together which may help in formatting some of my more complex expressions, so thanks.
