### DISCUSSION TITLE
Ansible dynamic inventory issue

### DISCUSSION THREAD

**Discussion by TheeMadWhiteHatter** [netbox-community/netbox#8016] [General]
When trying to set Netbox as an inventory source in Ansible I am getting the following error: 

The complete exception is provided below:
</p> <pre><strong>&lt;class **&#x27**;ModuleNotFoundError**&#x27;&gt;</strong><br** />
No module named &#x27;jsonschema.compat&#x27;  Python version: 3.8.10 NetBox
version: 3.0.4

[WARNING]: Unable to parse /runner/project/netbox_inventory.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by candlerb** [comment]
Can you paste your `netbox_inventory.yml`, with passwords blanked out?

**Reply by TheeMadWhiteHatter** [reply]
---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://10.10.10.10
token: mytokeninfoinserthereabc123
validate_certs: false
config_context: false
host_key_checking: false
interfaces: true


I also changed the file name that it is pulling from to just hosts instead of netbox_inventory.yml. Now it at least populates in the drop down to select from. Still the same errors though. 
![image](https://user-images.githubusercontent.com/73369617/145310069-75b66f43-fe9c-47ee-8363-97fbbd7ffa0e.png)

**Reply by TheeMadWhiteHatter** [reply]
Also it is AWX version 18, on a minikube cluster on a Centos7 VM.

**Comment by candlerb** [comment]
I'm using standalone ansible 2.10.10, not AWX/Tower, under Ubuntu 18.04.  Here's my config:

#### ansible.cfg

```
[defaults]
inventory = netbox.yaml
host_key_checking = False
nocows = 1
retry_files_enabled = False

[inventory]
enable_plugins = netbox, ini
```

#### netbox.yaml

```
# Requires:
# ansible-galaxy collection install netbox.netbox
#
# To test:
# ansible-inventory -v --list -i netbox.yaml

plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.example.net/
token: XXXXXXXX
validate_certs: True

# Do not use config_context unless patch has been applied to
# /usr/lib/python2.7/dist-packages/ansible/plugins/inventory/netbox.py
# See: https://github.com/ansible/ansible/pull/65431
config_context: True
group_by:
  - sites
  - device_roles
  # Grouping by tags for Netbox 2.9 fixed by https://github.com/netbox-community/ansible_modules/pull/333
  - tags
query_filters:
  - tag: ansible
  - status: active
```

Then running `ansible-inventory --list` will list all the devices and VMs downloaded from Netbox, and `ansible -m ping all` will connect to them.

What I suggest is that you get standalone ansible working fine.  When that works, if you still have a problem with AWX, then that is something you can take up on an AWX-specific mailing list.

Your config looks reasonable to me, except that "host_key_checking" doesn't belong in the inventory config (it belongs in the ansible defaults).  The set of allowed parameters is shown [here](https://docs.ansible.com/ansible/latest/collections/netbox/netbox/nb_inventory_inventory.html).
