### DISCUSSION TITLE
Unify interface parents?

### DISCUSSION THREAD

**Discussion by candlerb** [netbox-community/netbox#8110] [Ideas]
Just raising this for discussion.

As of Netbox 3.1, interfaces can now link to three types of related interface:

* Parent
* LAG
* Bridge

I cannot think of any case where you might use more than one of these at once on the same interface.

If this were simplified to just "Parent", the type of relationship would be inferred by the type of the parent interface: i.e. if the parent interface is a LAG or a Bridge, then that would be the same as linking to "LAG" or "Bridge" today.

One benefit of this is that (optionally) the interfaces could be displayed naturally in a tree: nest the child interfaces below the parent.  Another benefit would be fewer columns required in the display.

Thoughts?

**Comment by candlerb** [comment]
Never mind, I found a case where both 'parent' and 'bridge' are required.  In [netplan](https://netplan.io/)-ese:

```
network:
  version: 2
  ethernets:
    enp2s0f0:
      wakeonlan: true
      dhcp4: false
      accept-ra: false
      link-local: []
  vlans:
    vlan254:
       id: 254
       link: enp2s0f0
       accept-ra: false
       link-local: []
  bridges:
    br254:
      interfaces: [vlan254]
      parameters:
        stp: false
        forward-delay: 0
      dhcp4: false
      addresses: [10.12.254.5/24]
```

Here, interface `vlan254` is a subinterface of `enp2s0f0` (in earlier systems it would be called `enp2s0f0.254`).  However it is also a member of bridge `br254`.  Hence in Netbox:

![image](https://user-images.githubusercontent.com/44789/146915101-baabb839-1eb2-4956-b8ee-4b9012455237.png)
