### DISCUSSION TITLE
nb_inventory

### DISCUSSION THREAD

**Discussion by MercifulCamel** [netbox-community/netbox#8930] [Q&A]
I'm probably just missing something somewhere but I cant seem to wrap my head around it so thought I would ask here.
So I currently have a inventory file that looks like this

```
# inventory file - vdi
plugin: netbox.netbox.nb_inventory
api_endpoint: http://localhost:8000
token: ##
validate_certs: false

group_by:
  - tags

query_filters:
  - tag: vdi
  - status: "staged"

compose:
  os: custom_fields.server_os
  vm_id: id
  status: status.label
  tenant_id: tenant.slug
  tenant_netbox_id: tenant.id
  vm_cluster: cluster.name
  vm_cluster_id: cluster.id
  vm_vcpus: vcpus
  vm_disk: disk
  vm_memory: memory
  vm_name: name
  vgpu_type: custom_fields.vgpu
  vdi_host: primary_ip4.address

```
I'm currently trying to get it too gather variables from Netbox and then run it against the hosts in /etc/ansible/hosts and check if there are available resources too run VMs with vGPUs.
