### DISCUSSION TITLE
Any way to sync groups with SSO?

### DISCUSSION THREAD

**Discussion by gboor** [netbox-community/netbox#9635] [Q&A]
I have configured Netbox to authenticate against Keycloak and that works very well, there only doesn't seem to be a way to sync groups and/or assign staff/superuser based on group membership.

With the RemoteUserBackend you can set which HTTP header contains groups and which groups grant superuser or staff status. The token I authenticate with includes the groups, but I can't figure out how to make them sync.

Is this possible at all?

**Comment by candlerb** [comment]
I couldn't get group sync to work with the python-social-auth stuff, but it's working with RemoteUserBackend.

I run `mod_auth_openidc` on the Apache reverse proxy which sits on the Netbox server in front of gunicorn.

### Netbox configuration

```
# Remote authentication support
REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_BACKEND = 'netbox.authentication.RemoteUserBackend'
REMOTE_AUTH_HEADER = 'HTTP_REMOTE_USER'
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_DEFAULT_GROUPS = []
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}
REMOTE_AUTH_GROUP_HEADER = 'HTTP_OIDC_CLAIM_ROLES'
REMOTE_AUTH_GROUP_SYNC_ENABLED = True
REMOTE_AUTH_GROUP_SEPARATOR = ','
REMOTE_AUTH_STAFF_GROUPS = ['netbox:staff']
REMOTE_AUTH_SUPERUSER_GROUPS = ['netbox:superuser']
```

Also, you need to create groups in Netbox called "netbox:access", "netbox:staff" and "netbox:superuser" manually, before you turn on REMOTE_AUTH_ENABLED.

### Apache configuration

```
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    ProxyPass / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/

    OIDCProviderMetadataURL https://keycloak.example.net/realms/example.net/.well-known/openid-configuration
    OIDCClientID netbox
    OIDCClientSecret XXXXXXXX

    OIDCRedirectURI /oauth2callback
    OIDCCryptoPassphrase XXXXXsome-random-stringXXXXX
    OIDCScope "openid email profile roles"
    OIDCSessionInactivityTimeout 43200
    OIDCCookieSameSite On
    #Only available in mod_auth_openidc 2.3.8+:
    OIDCStateMaxNumberOfCookies 7 true

    # Note that OIDC Providers (OP) don't guarantee the uniqueness of these claims
    #OIDCRemoteUserClaim email
    OIDCRemoteUserClaim preferred_username
    OIDCPassUserInfoAs claims
    OIDCPassClaimsAs headers
    RequestHeader unset REMOTE_USER
    RequestHeader set REMOTE_USER expr=%{REMOTE_USER}

    <Location />
        AuthType openid-connect
        Require claim roles:netbox:access
        AuthzSendForbiddenOnFailure on
    </Location>

    <Location /api/>
        <RequireAny>
            AuthType openid-connect
            Require claim roles:netbox:access
            # Allow access to /api/ with token instead of OIDC Auth
            # https://httpd.apache.org/docs/2.4/howto/access.html#env
            Require expr "%{HTTP:Authorization} =~ /^Token /"
        </RequireAny>
        AuthzSendForbiddenOnFailure on
    </Location>
```

### Keycloak configuration

I use Keycloak client roles, rather than groups, to control Netbox.  This is more flexible, since you can add client roles to one or more groups as well as to individual users; it means the policy of *who* can do what is centralised in Keycloak, and Netbox doesn't know or care.

To create the client:

* Clients > Add
* Enter client ID: "netbox"
* "Settings" tab
    * set "Access Type" to "Confidential"
    * set "Valid Redirect URIs" to https://netbox.example.net/oauth2callback
    * click Save
* A new tab "Credentials" appears: get the client secret from here
* "Roles" tab: create roles "netbox:access", "netbox:staff" and "netbox:superuser"
* "Mappers" tab: "Add builtin", select "Client roles", click "Add selected"

You can add these roles selectively to groups.  For example, if you have an "Admin" group which needs them all:

* Groups > Admin > Edit
* Role Mappings; Client Roles > Netbox
* add "netbox:access", "netbox:staff" and "netbox:superuser"

You also have to configure Keycloak to expose these roles as a flat list in the ID token:

* Clients > netbox > Mappers
* Add builtin; check "client roles"
* Click on "client roles"
* Change "Token claim name" to "roles"
* Change "Add to ID token" to On
* Save

Use `tcpdump -i lo -nn -s0 -A tcp port 8001` to look at traffic going between the proxy and gunicorn.  With this setting, you should see (for someone in the Admin group):

```
OIDC_CLAIM_roles: netbox:access,netbox:superuser,netbox:staff
```

### Groups and roles

With this config, only users with "netbox:access" role are allowed to see Netbox, and the staff/superuser privileges work as expected.  You can also create other roles which will sync as Netbox groups.  (Note: these groups aren't *created* automatically in Netbox; I saw a [patch](https://github.com/netbox-community/netbox/issues/7671) which added `REMOTE_AUTH_AUTO_CREATE_GROUPS` but I don't think it's merged yet. What is synced is your *membership* of these groups, if they already exist as Netbox groups)

You don't have to prefix the role names with "netbox:".  I just did so to make it clear what they were for (and because I was using groups instead of client roles previously)

You don't have to use the client roles if you don't want.  You should be able to configure Keycloak to expose a 'groups' claim in the ID token, and modify the Apache config to use that.  But then Netbox will need to see lots of groups that it doesn't care about; and you'll have to configure in Netbox itself the policy of which organizational groups are allowed to do what.

------

Aside: Since getting it to work with Keycloak, I've moved to using Vault as OIDC provider. That doesn't have any concept of "roles" so I'm using groups for that.  Its web UI isn't as good as Keycloak for user management, but on the plus side it doesn't use java so it's much more lightweight, and it offers a whole bunch of other functionality including an SSH certificate authority.

**Reply by gboor** [reply]
I was already able to do this with REMOTE_AUTH and oauth2-proxy, which worked fine for syncing groups. I switched to the built-in SSO auth using social_core.backends.keycloak.KeycloakOAuth2 - which works too.

REMOTE_AUTH settings are no longer available. I was just wondering if I could sync groups with pure SSO, but it looks like it will require a proxy of some sort and REMOTE_AUTH to be able to do that. Am I understanding that correctly?

Would it be technically possible to achieve this with some changes? I could look into making an MR for it...

**Reply by candlerb** [reply]
>  I was just wondering if I could sync groups with pure SSO

By "pure SSO" do you mean with `social_core.backends.<foo>`?  I spent [quite a lot of time](https://github.com/python-social-auth/social-core/pull/669) on this, but as I said, I wasn't able to get it to work.

What happens is: if you modify the PSA backend to return a list of strings as a 'groups' attribute from `get_user_details()`, then Django [barfs](https://github.com/python-social-auth/social-core/issues/690).  I couldn't work out how to fix this.

**Reply by gboor** [reply]
Thanks for the very complete breakdown. That's certainly a shame...

It does seem to me that this can be fixed in social-auth, no? Especially because it seems to work for other backends... I will try to do some testing. Thanks for the pointers!

**Comment by mtinberg** [comment]
Yes, this should work.  You need to tell Netbox configure.py which header is used for the group info (eg. X-MyGroups or isMemberOf) and what record separator is used when the identity is members of multiple groups (eg, ',' or ':' or whatever) then you need to create matching group names in Netbox, you can also specify in configure.py a group that should toggle the Staff or Superuser bit, which is in the docs.  If it's not clear which header has the info then you can tcpdump/wireshark the connection between the https proxy server and the http uWSGI/gunicorn process manager or create a dummy CGI that just prints out the environment so you can see exactly what is being passed to the application from the http server

eg. from my ansible config

          REMOTE_AUTH_ENABLED: True
          REMOTE_AUTH_BACKEND: "netbox.authentication.RemoteUserBackend"
          REMOTE_AUTH_HEADER: 'HTTP_X_MYAUTH' #REMOTE_USER is also common
          REMOTE_AUTH_GROUP_HEADER: 'HTTP_X_MYGROUPS' #this may be auth-provider specific
          REMOTE_AUTH_GROUP_SEPARATOR: ';'
          REMOTE_AUTH_GROUP_SYNC_ENABLED: True
          REMOTE_AUTH_AUTO_CREATE_USER: True
          REMOTE_AUTH_DEFAULT_GROUPS:
            - my:saml:group1
          REMOTE_AUTH_STAFF_GROUPS:
            - my:saml:group2
          REMOTE_AUTH_SUPERUSER_GROUPS:
            - my:saml:group3
          REMOTE_AUTH_DEFAULT_PERMISSIONS: {}

Simple test CGI (do not leave on an active public server so it doesn't give away info you don't want)

#! /usr/bin/perl -T

use warnings;
use strict;

use CGI;
use Data::Dumper;
$Data::Dumper::Sortkeys=1;
my $cgi = CGI->new();
print $cgi->header('text/plain');
print(Dumper($ENV));


—

Mark Tinberg ***@***.***>

Division of Information Technology-Network Services

University of Wisconsin-Madison


________________________________
From: Gerard ***@***.***>
Sent: Thursday, June 30, 2022 7:39 AM
To: netbox-community/netbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [netbox-community/netbox] Any way to sync groups with SSO? (Discussion #9635)


I have configured Netbox to authenticate against Keycloak and that works very well, there only doesn't seem to be a way to sync groups and/or assign staff/superuser based on group membership.

With the RemoteUserBackend you can set which HTTP header contains groups and which groups grant superuser or staff status. The token I authenticate with includes the groups, but I can't figure out how to make them sync.

Is this possible at all?

**Reply by gboor** [reply]
See my reply to the earlier post - I know it can be done with REMOTE_AUTH and some proxy, but I'd like it to work with the built-in SSO.

**Comment by jschewebbn** [comment]
Based on the discussion here it looks like I need a webserver module to get group information into netbox when using an external authentication provider. Is that correct? Has anyone gotten it to work using the build-in SSO setup?

**Comment by jose-hernandez2** [comment]
I know this thread is old, but did anyone find a way to do this? We are also trying to sync groups using `social_core.backends.keycloak.KeycloakOAuth2`, but couldn’t find a way so far..

**Reply by candlerb** [reply]
People have apparently done it by inserting custom python code into the authentication pipeline. What I've seen seems mainly people using Azure AD rather than Keycloak, but I did find a Keycloak example [here](https://github.com/netbox-community/netbox/discussions/8579#discussioncomment-5758416).

Try searching for `SOCIAL_AUTH_PIPELINE` in the discussions archive, e.g. #9216. You'll also find cases of people who can't get it to work, e.g. #13129

**Comment by jschewebbn** [comment]
I ended up using mod_auth_oidc with Apache and then the REMOTE_AUTH plugin for netbox.

**Comment by marsteel** [comment]
> I ended up using mod_auth_oidc with Apache and then the REMOTE_AUTH plugin for netbox.

@jschewebbn  @jose-hernandez2
To do SSO group sync without reverse proxy, you can follow https://github.com/netbox-community/netbox-chart/blob/develop/docs/auth.md and https://github.com/netbox-community/netbox/discussions/12747 to add a new netbox.sso_pipeline_roles.set_role pipeline to SOCIAL_AUTH_PIPELINE in extra.py or settings.py

"netbox.sso_pipeline_roles.set_role" points to /opt/netbox/netbox/sso_pipeline_roles.py

Create a python script file as /opt/netbox/netbox/netbox/sso_pipeline_roles.py

set_role() in sso_pipeline_roles.py will parse SSO user groups passed from IdP and add the user to local netbox groups.

My version is at https://github.com/marsteel/netbox-docker/blob/release/.netbox/netbox/netbox/sso_pipeline_roles.py.

**Reply by jose-hernandez2** [reply]
Hi @marsteel ,

Yes, thank you for your answer. I was able to get the groups from Keycloak as described in the documentation that @candlerb provided me, which is basically what you mentioned as well. However, when I updated to Netbox v.4.0.1, it was necessary to change a few things in the sso_pipeline_roles.py as described here: https://github.com/netbox-community/netbox/discussions/16098
In my case I had to change the Group import from `django.contrib.auth.models import Group` to `netbox.authentication import Group` and at the end of the script, change the group assignment to be done using `group.users.add(user)`. Otherwise, I would get the error mentioned in the GitHub Discussion ('Group' object has no attribute 'user_set').

**Reply by marsteel** [reply]
@jose-hernandez2 

Thank you for the reminder for this change. 
Starting with Netbox v4.0.x , the "Group" in similiar statement of kinds of customized sso_pipeline_roles.py is empty if it is from "from django.contrib.auth.models import Group"

```
from django.contrib.auth.models import Group
  groups = Group.objects.all()

#Debug
  print("All available groups in Netbox setting: ")
  print(groups)
```
The Group is empty. As Group is empty, any logic iterating over this Emply group and adding user to each returned group item will break.

```
May 15, 2024 at 10:52 (UTC+2:00) | All available groups in Netbox setting: | netbox-container
May 15, 2024 at 10:52 (UTC+2:00) | <QuerySet []> | netbox-container
```

I have fixed my script accordingly.

**Comment by younsl** [comment]
Spent an entire day on Keycloak group-to-NetBox permission mapping. Here's the fix.

<details>
<summary>NetBox SSO: Keycloak Group-Based Permission Mapping Guide</summary>

## Overview

This guide explains how to integrate NetBox with Keycloak OIDC for SSO authentication in a Kubernetes environment using the [netbox-chart](https://github.com/netbox-community/netbox-chart).

Key features:

- Auto user creation on first login
- Auto permission assignment based on Keycloak groups:
  - `administrator` group → Superuser + Staff
  - `developer` group → Staff
  - Others → Regular user

## NetBox Permission Model

| Role | Description |
|------|-------------|
| **Superuser** | Full admin access. Can manage all objects, users, and system settings |
| **Staff** | Can access Django admin panel. Permissions controlled by assigned groups |
| **Regular user** | No admin access. Can only view/edit objects based on assigned permissions |

## Why Custom Pipeline?

NetBox uses [python-social-auth](https://python-social-auth.readthedocs.io/) for OAuth/OIDC authentication.

NetBox's built-in `groupSyncEnabled` and `superuserGroups` only work with HTTP header-based authentication (e.g., Apache mod_auth_openidc). For python-social-auth (direct OAuth), NetBox does not automatically read the groups claim from tokens. A custom pipeline is required to map Keycloak groups to NetBox permissions.

References:

- [python-social-auth](https://python-social-auth.readthedocs.io/)
- [python-social-auth Keycloak Backend](https://python-social-auth.readthedocs.io/en/latest/backends/keycloak.html)
- [social-core keycloak.py](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/keycloak.py)
- [NetBox SSO Group Sync Discussion](https://github.com/netbox-community/netbox/discussions/9635) - Community discussion about group synchronization limitations with SSO

## Prerequisites

- Kubernetes cluster
- NetBox Community v4.4.8-Docker-3.4.2 deployed via [netbox-chart](https://github.com/netbox-community/netbox-chart)
- Keycloak with a realm configured

## Keycloak Configuration

### Create Client

| Setting | Value |
|---------|-------|
| Client ID | `netbox` |
| Client Protocol | `openid-connect` |
| Access Type | `confidential` |

### Add Mappers

Go to Clients → netbox → Client Scopes → netbox-dedicated → Mappers.

**Audience Mapper:**

| Field | Value |
|-------|-------|
| Mapper Type | Audience |
| Included Client Audience | `netbox` |
| Add to access token | ON |

**Groups Mapper:**

| Field | Value |
|-------|-------|
| Mapper Type | Group Membership |
| Token Claim Name | `groups` |
| Full group path | OFF |
| Add to access token | ON |

### Get Public Key

```bash
curl -s https://<keycloak>/realms/<realm> | jq -r '.public_key'
```

You can also get the public key from Keycloak Admin Console: Realm settings → Keys → RS256 → Public key button.

## Values Configuration

Configure netbox's helm chart values file to enable Keycloak OIDC authentication with custom pipeline.

The custom pipeline script is deployed as a ConfigMap via netbox subchart's `extraDeploy` and mounted to the netbox-app pod at `/opt/netbox/netbox/netbox/sso_pipeline.py`. This allows NetBox to import and execute it as a Python module (`netbox.sso_pipeline.set_superuser`) during the authentication process.

```yaml
netbox-operator:
  netbox:
    extraConfig:
      - values:
          SOCIAL_AUTH_PIPELINE:
            # ... omitted for brevity ...
            - netbox.sso_pipeline.set_superuser
```

The group names in the script (`administrator`, `developer`) must match your Keycloak group names exactly (case-sensitive).

```yaml
netbox-operator:
  netbox:
    enabled: true

    ## Keycloak OIDC SSO settings
    remoteAuth:
      enabled: true
      backends:
        - social_core.backends.keycloak.KeycloakOAuth2
      autoCreateUser: true
      autoCreateGroups: true
      defaultGroups: []
      defaultPermissions: {}
      # NOTE: groupSyncEnabled, superuserGroups, staffGroups only work with
      # HTTP header-based auth (e.g., Apache mod_auth_openidc).
      # For python-social-auth, use custom pipeline instead.
      groupSyncEnabled: true
      superuserGroups:
        - administrator
      superusers: []
      staffGroups:
        - developer
      staffUsers: []

    extraConfig:
      - values:
          SOCIAL_AUTH_KEYCLOAK_KEY: "netbox"
          SOCIAL_AUTH_KEYCLOAK_SECRET: "<client-secret>"
          SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: "<public-key>"
          SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: "https://<keycloak>/realms/<realm>/protocol/openid-connect/auth"
          SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: "https://<keycloak>/realms/<realm>/protocol/openid-connect/token"
          SOCIAL_AUTH_KEYCLOAK_SCOPE:
            - openid
            - email
            - profile
          SOCIAL_AUTH_KEYCLOAK_ID_KEY: "email"
          LOGIN_REQUIRED: true
          # Authentication pipeline - executed in order during login
          SOCIAL_AUTH_PIPELINE:
            - social_core.pipeline.social_auth.social_details   # Extract user details from OAuth response
            - social_core.pipeline.social_auth.social_uid       # Get user's unique ID
            - social_core.pipeline.social_auth.auth_allowed     # Check if authentication is allowed
            - social_core.pipeline.social_auth.social_user      # Find existing social account
            - social_core.pipeline.user.get_username            # Generate username
            - social_core.pipeline.user.create_user             # Create new user if needed
            - social_core.pipeline.social_auth.associate_user   # Link social account to user
            - social_core.pipeline.social_auth.load_extra_data  # Load extra data (groups, etc.)
            - social_core.pipeline.user.user_details            # Update user details
            - netbox.sso_pipeline.set_superuser                 # Custom: Map Keycloak groups to NetBox permissions

    # Mount custom pipeline to netbox-app pod
    extraVolumes:
      - name: sso-pipeline
        configMap:
          name: netbox-sso-pipeline

    extraVolumeMounts:
      - name: sso-pipeline
        mountPath: /opt/netbox/netbox/netbox/sso_pipeline.py
        subPath: sso_pipeline.py

    # Custom pipeline ConfigMap
    extraDeploy:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: netbox-sso-pipeline
        data:
          sso_pipeline.py: |
            def set_superuser(backend, user, response, *args, **kwargs):
                groups = response.get('groups', [])
                normalized = [g.lstrip('/') for g in groups]

                if 'administrator' in normalized:
                    user.is_superuser = True
                    user.is_staff = True
                elif 'developer' in normalized:
                    user.is_staff = True
                else:
                    user.is_superuser = False
                    user.is_staff = False

                user.save()
```

Note: `groupSyncEnabled`, `superuserGroups`, `staffGroups` settings are included but only work with HTTP header-based authentication. For python-social-auth (direct OAuth), the custom pipeline handles group mapping.

## Group Mapping

| Keycloak Group | NetBox Permission |
|----------------|-------------------|
| `administrator` | superuser + staff |
| `developer` | staff only |
| others | regular user |

## Troubleshooting

### InvalidAudienceError

Missing audience mapper in Keycloak client configuration.

Add Audience mapper in Keycloak: Clients → netbox → Client Scopes → netbox-dedicated → Mappers → Add Audience mapper.

### sequence item 1: NoneType

Missing groups claim or user name fields in the token.

Add Groups mapper in Keycloak and ensure the user has first/last name set in their Keycloak profile.

### Login works but no superuser

NetBox's built-in `groupSyncEnabled` and `superuserGroups` only work with HTTP header-based authentication. For python-social-auth (direct OAuth), a custom pipeline is required to read groups from the token and assign permissions.

The custom pipeline must be mounted at `/opt/netbox/netbox/netbox/sso_pipeline.py`. Check extraVolumeMounts path and verify the ConfigMap is created in the correct namespace. You can verify the file is mounted by exec into the netbox pod and checking the file exists.

## Conclusion

Automatically creating users and mapping Keycloak groups to NetBox permissions (Staff/Superuser) is not straightforward. NetBox's built-in group sync only supports HTTP header-based authentication, not direct OAuth.

Solution:

1. Create a custom python-social-auth pipeline that reads groups claim from token
2. Deploy it as a ConfigMap via extraDeploy
3. Mount it to netbox-app pod via extraVolumes/extraVolumeMounts
4. Add the custom function to SOCIAL_AUTH_PIPELINE

This approach was inspired by [NetBox with Okta SSO using OAuth](https://blog.networktocode.com/post/netbox-with-okta-sso-oauth/), which demonstrates custom pipeline implementation for similar OAuth providers.

</details>
