### ISSUE TITLE
netbox_device_interface_template A- llow bulk creation 

### ISSUE THREAD

**Issue by jsalatiel** [netbox-community/netbox#10507]
### NetBox version

v3.2.5

### Python version

3.8

### Steps to Reproduce

```
- name: Adding ports
  netbox.netbox.netbox_device_interface_template:
    data:
      device_type: some_device
      name: '[ge,xe]-0/0/[0-9]] '
      type: 1000BASE-T
```

### Expected Behavior

Just like the behaviour on the webui, the following interfaces should have been created:
![image](https://user-images.githubusercontent.com/5522389/193078696-f6568962-72d7-4251-b113-6185fbe52207.png)

### Observed Behavior

One single interface named [ge,xe]-0/0/[0-9]] is created
