### ISSUE TITLE
Cannot import or clone a Cable

### ISSUE THREAD

**Issue by Qwiko** [netbox-community/netbox#11210]
### NetBox version

v3.4.0

### Python version

3.9

### Steps to Reproduce

1. Import Cables
2. Add data to import a cable
3. Click Import

### Expected Behavior

A cable should be created.

### Observed Behavior

A ValueError was raised.
Creating a cable through the UI is done successfully.
Using the API creates the same error as importing.

```
<class 'ValueError'>

'Cable' instance needs to have a primary key value before this relationship can be used.

Python version: 3.9.2
NetBox version: 3.4.0
```

There seems to also be an issue with Cloning a Cable:
When you click Clone on a Cable you recieve this error:

```
<class 'AttributeError'>

'str' object has no attribute 'label'

Python version: 3.9.2
NetBox version: 3.4.0
```

**Comment by Qwiko** [comment]
If you provide the id for a cable it is updated correctly. This error is only when trying to import new cable objects.

**Comment by kkthxbye-code** [comment]
> Add data to import a cable

Please provide all the steps required to replicate the issue, including example CSV data.

> Using the API creates the same error as importing.

Please provide replication steps for the API error also.

> There seems to also be an issue with Cloning a Cable:

This should probably be split out in a seperate bug report as they are unlikely to be related. I'm not even sure why it is possible to clone a cable as no fields are cloned and we don't provide a default "Add cable" option like most other models.

**Comment by kkthxbye-code** [comment]
For reference I just tried importing the following cable and it worked without issue on 3.4.0:

```
side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name
dmi01-yonkers-sw01,dcim.interface,GigabitEthernet1/0/6,dmi01-yonkers-sw01,dcim.interface,GigabitEthernet1/0/7
```

**Comment by Qwiko** [comment]
Then it must be in my environment.
Sorry for the inconvenience.
Closing this issue.

**Comment by jordanrvillarreal** [comment]
I'm seeing similar behavior.  It feels like there are certain errors that aren't being caught.  While trying to bulk create if I had a bad interface type or name it would create the same primary key error but when I had included additional data in the cable color I received a specific error saying I provided 7 characters but it was only expecting 6.

**Comment by MasterWigu** [comment]
I'm also seeing similar behavior. When creating new cables using the import feature (using a json snippet), it shows the same `'Cable' instance needs to have a primary key value before this relationship can be used.`. I can also confirm that the cables I'm adding have only the required fields set.

**Comment by sc68cal** [comment]
I can reproduce this via trivial examples with our Ansible modules as well, with the latest from NetBox docker images 

```yaml
cables: 
  - a_device: clab-ipamexample-spine1
    a_name: e1-1
    b_device: clab-ipamexample-spine2
    b_name: e1-1
```

```yaml
- hosts: localhost
  gather_facts: False
  tags:
    - cables
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "http://localhost:8000"
      netbox_token: "0123456789abcdef0123456789abcdef01234567"
      validate_certs: False
  tasks:
    - name: Create cables for spine links
      netbox_cable:
        data:
          termination_a_type: dcim.interface
          termination_a:
            device: "{{ item.a_device }}"
            name: "{{ item.a_name }}"
          termination_b_type: dcim.interface
          termination_b:
            device: "{{ item.b_device }}"
            name: "{{ item.b_name }}"
        state: present
      loop: "{{ cables }}"
```

This is supposed to be the minimal required amount of information, via our docs - https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/netbox_cable_module.html#ansible-collections-netbox-netbox-netbox-cable-module
