### ISSUE TITLE
Add CSS class to elevation SVG styles to avoid any styles conflict when integrating elevation in a third party app

### ISSUE THREAD

**Issue by Wait4Code** [netbox-community/netbox#11898]
### NetBox version

3.4.3

### Feature type

Data model extension

### Proposed functionality

I think that SVG tag of elevations should have a specific CSS class and all its styles should be prefixed with that class.

### Use case

I'm storing elevation SVG code in a third party app via netbox APIs.
I'm trying to display theses SVG in my app but when I integrate them, my styles are broken, especially because of the following rule in SVG styles :
```CSS
*{
    font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,Liberation Sans,sans-serif,"Apple Color Emoji","Segoe UI Emoji",Segoe UI Symbol,"Noto Color Emoji";
    font-size:.875rem
}
```

To get around this problem, I'm using object HTML tag but I think it would be nice if elevations styles could be more isolated.
