### ISSUE TITLE
Cable bulk import with ID do not update cables

### ISSUE THREAD

**Issue by clementTal** [netbox-community/netbox#11987]
### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce

1. create a manufacturer using csv:
```
name,slug
manufacturer,manufacturer
```

2. create devicetype using yaml:
```
manufacturer: manufacturer
model: device_type_model
slug: device_type_model
part_number: ''
u_height: 1.0
is_full_depth: false
subdevice_role: ''
airflow: ''
comments: ''
interfaces:
- name: interface_A
  type: 1000base-t
  mgmt_only: false
  label: ''
  description: ''
  poe_mode: ''
  poe_type: ''
```

3. create a device role using csv:
```
name,slug,color
device_type,device_type,ffffff
```

4. create a site using csv:
```
name,slug,status
site,site,active
```

5. create 3 devices using csv:
```
name,role,manufacturer,device_type,status,site
device_1,device_type,manufacturer,device_type_model,active,site
device_2,device_type,manufacturer,device_type_model,active,site
device_3,device_type,manufacturer,device_type_model,active,site
```

6. create a cable to link both created devices interfaces using csv:
```
side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name
device_1,dcim.interface,interface_A,device_2,dcim.interface,interface_A
```

7. get the cable id after creation, and edit the csv to link the cable to other device (replace <CABLE_ID> with correct value):
```
id,side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name
<CABLE_ID>,device_1,dcim.interface,interface_A,device_3,dcim.interface,interface_A
```

### Expected Behavior

The cable described should be updated

### Observed Behavior

Record 1 side_a_name: Side A: device_1 interface_A is already connected
