### ISSUE TITLE
netbox_device_interface module cannot create a WWN property

### ISSUE THREAD

**Issue by artiomello** [netbox-community/netbox#12254]
### NetBox version

v3.4.7

### Python version

3.8

### Steps to Reproduce

I'm using AWX to create device interfaces using a loop:
```yaml
  - name: Creating device interfaces
    netbox.netbox.netbox_device_interface:
      data: "{{ interface }}"
      state: present
    loop: "{{ interfaces }}"
    loop_control:
      loop_var: interface
      label: "{{ interface.device, interface.name }}"
    tags: deviceiface
```
and passing to it the following arguments:
```yaml
  - device: device_name
    name: "SAS1: P2"
    type: Other
    description: HPE Smart Array E208e-p SR Gen10
    duplex: auto
    speed: 12000000
    tags: "{{ defaults.tags }}"
    wwn: 200050EB12121212
```

### Expected Behavior

WWN property is populated.

### Observed Behavior

```json
{
  "msg": "Unsupported parameters for (netbox.netbox.netbox_device_interface) module: data.wwn. Supported parameters include: data, netbox_token, query_params, cert, netbox_url, update_vc_child, validate_certs, state.",
  "invocation": {
    "module_args": {
      "netbox_url": "https://netbox",
      "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "validate_certs": "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt",
      "data": {
        "device": "device_name",
        "name": "SAS1: P2",
        "type": "Other",
        "description": "HPE Smart Array E208e-p SR Gen10",
        "duplex": "auto",
        "speed": 12000000,
        "tags": [
        ],
        "wwn": "200050EB12121212",
        "form_factor": null,
        "label": null,
        "enabled": null,
        "lag": null,
        "bridge": null,
        "mtu": null,
        "mac_address": null,
        "mgmt_only": null,
        "poe_type": null,
        "poe_mode": null,
        "mode": null,
        "vrf": null,
        "parent_interface": null,
        "untagged_vlan": null,
        "tagged_vlans": null,
        "mark_connected": null,
        "custom_fields": null
      },
      "state": "present",
      "update_vc_child": false,
      "query_params": null,
      "cert": null
    }
  },
  "_ansible_no_log": false,
  "changed": false,
  "interface": {
    "device": "device_name",
    "name": "SAS1: P2",
    "type": "Other",
    "description": "HPE Smart Array E208e-p SR Gen10",
    "duplex": "auto",
    "speed": 12000000,
    "tags": [
    ],
    "wwn": "200050EB12121212"
  },
  "ansible_loop_var": "interface",
  "_ansible_item_label": "('device_name', 'SAS1: P2')"
}
```

It works fine without the `wwn` property, which probably doesn't even exist.
