### ISSUE TITLE
Importing device type yaml results in type error

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#13285]
### NetBox version

v3.5.6

### Python version

3.9

### Steps to Reproduce

1. Create a manufacturer named Juniper
2. Import the following data (copied from the [Juniper MX204](https://github.com/netbox-community/devicetype-library/blob/master/device-types/Juniper/MX204.yaml) definition in the device type library)

```
---
---
manufacturer: Juniper
model: MX204
slug: juniper-mx204
interfaces:
  - name: fxp0
    type: 1000base-t
    mgmt_only: true
  - name: et-0/0/0
    type: 100gbase-x-qsfp28
  - name: et-0/0/1
    type: 100gbase-x-qsfp28
  - name: et-0/0/2
    type: 100gbase-x-qsfp28
  - name: et-0/0/3
    type: 100gbase-x-qsfp28
  - name: xe-0/1/0
    type: 10gbase-x-sfpp
  - name: xe-0/1/1
    type: 10gbase-x-sfpp
  - name: xe-0/1/2
    type: 10gbase-x-sfpp
  - name: xe-0/1/3
    type: 10gbase-x-sfpp
  - name: xe-0/1/4
    type: 10gbase-x-sfpp
  - name: xe-0/1/5
    type: 10gbase-x-sfpp
  - name: xe-0/1/6
    type: 10gbase-x-sfpp
  - name: xe-0/1/7
    type: 10gbase-x-sfpp
power-ports:
  - name: PSU0
    type: iec-60320-c14
    maximum_draw: 650
  - name: PSU1
    type: iec-60320-c14
    maximum_draw: 650
console-ports:
  - name: Console
    type: rj-45
```

### Expected Behavior

Import succeeds

### Observed Behavior

```<class 'TypeError'>

unsupported operand type(s) for %: 'float' and 'decimal.Decimal'
```
