### ISSUE TITLE
TLS is not established when connecting to Redis Sentinel

### ISSUE THREAD

**Issue by skonefal** [netbox-community/netbox#13770]
### NetBox version

v3.5.9

### Python version

3.10

### Steps to Reproduce

Deploy Redis replicated in Sentinel mode and configure Netbox as follows:

```
REDIS:
  tasks:
    SENTINELS: ["redis-node-0.redis-headless:26379","redis-node-1.redis-headless:26379","redis-node-2.redis-headless:26379"]
    SENTINEL_SERVICE: "netbox-redis"
    SENTINEL_TIMEOUT: 300
    USERNAME: 
    DATABASE: 0
    SSL: true
    INSECURE_SKIP_TLS_VERIFY: true
    CA_CERT_PATH: "/etc/ssl/redis_ca"
  caching:
    SENTINELS: ["redis-node-0.redis-headless:26379","redis-node-1.redis-headless:26379","redis-node-2.redis-headless:26379"]    
    SENTINEL_SERVICE: "netbox-redis"
    SENTINEL_TIMEOUT: 300
    USERNAME: 
    DATABASE: 1
    SSL: true
    INSECURE_SKIP_TLS_VERIFY: true
    CA_CERT_PATH: "/etc/ssl/redis_ca"
```

### Expected Behavior

Netbox should connect to Sentinel using TLS and retrieve Redis Master server and port.

### Observed Behavior

When Netbox tries to reach out to Sentinel to retrieve current Redis Master I receive following error:
```
No master found for 'netbox-redis': 
Redis<ConnectionPool<Connection<host=redis-node-0.redis-headless,port=26379,db=0>>> - ConnectionError("Error while reading from redis-node-0.redis-headless:26379 : (104, 'Connection reset by peer')"),
Redis<ConnectionPool<Connection<host=redis-node-1.redis-headless,port=26379,db=0>>> - ConnectionError("Error while reading from redis-node-1.redis-headless:26379 : (104, 'Connection reset by peer')"),
Redis<ConnectionPool<Connection<host=redis-node-2.redis-headless,port=26379,db=0>>> - ConnectionError("Error while reading from redis-node-2.redis-headless:26379 : (104, 'Connection reset by peer')")
```

I have validated that I can connect to Sentinel using CLI:
```
# redis-cli -h redis-node-0.redis-headless -p 26379 --tls --cacert ./redis-ca.crt 
redis-node-0.redis-headless:26379> SENTINEL get-master-addr-by-name netbox-redis
1) "redis-node-1.redis-headless.netbox.svc.cluster.local"
2) "6379"
```
From the other hand, when I do not specify TLS for redis-cli I reproduce the same issue seen in Netbox: 
```
# redis-cli -h redis-node-0.redis-headles -p 26379
redis-node-0.redis-headles:26379> SENTINEL get-master-addr-by-name netbox-redis
Error: Connection reset by peer
```

I could not find any additional TLS configuration for Redis Sentinel.
Do I miss anything in my configuration, or Netbox does not provide TLS configuration for Sentinel access?

Same configuration (without Sentinels) worked well when connecting to standalone Redis Master.
