### ISSUE TITLE
No error shown for duplicate component names in device type import

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#15185]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.8

### Steps to Reproduce

Go to Device Types > Import and paste in the following YAML

```
---
manufacturer: APC
model: AP7868-test
slug: apc-ap7868-test
u_height: 0
power-ports:
  - name: Power Port 1
    type: cs8365c
  - name: Power Port 2
    type: cs8365c
  - name: Power Port 2
    type: cs8365c
```

(trimmed from case in discussion #15182)

### Expected Behavior

An error to be displayed (ideally identifying the duplicate component name)

### Observed Behavior

Netbox silently returns to the import screen. There is no indication that there was an error, but the import does not complete.
