### ISSUE TITLE
Ansible Netbox integration doesn't work anymore after upgrading to NetBox 4.0.3 from NetBox 3.6.7

### ISSUE THREAD

**Issue by kiaz-github** [netbox-community/netbox#16414]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

```
      - name: "Netbox: create/update sites"
        netbox.netbox.netbox_site:
          netbox_url: "{{ nb_url }}"
          netbox_token: "{{ nb_token }}"
          validate_certs: no
          data:
            name: "RIZ-{{ item.Kuerzel }}-{{ item.ID }}"
            status: active
            site_group: "riz"
            tenant: "RIZ"
            time_zone: "Europe/Zurich"
            physical_address: "{{ item.Hauptstandort }} \n {{ item.Adresse }} \n {{ item.PLZ }} {{ item.Ort }}"
            comments: "NSN: {{ item.Anschlussnummer }}"
          state: present
        loop: "{{ standort.list }}"
        when:
          - item.ID.startswith('10')
          - item.Status in "{{ site_valid_status_list }}"
        tags:
          - create_site
```
          
         
          This playbook worked before the upgrade.
          

### Expected Behavior

The connection to the NeBox API works and the Ansible Playbook is executed.

### Observed Behavior

`"Failed to establish connection to NetBox API"`
