### ISSUE TITLE
Add custom CA Certificate

### ISSUE THREAD

**Issue by chaeynz** [netbox-community/netbox#16885]
### NetBox version

v4.0.2

### Feature type

New functionality

### Proposed functionality

As a user, I would like to add custom CA certificates to Netbox, so that outgoing Webhooks will not fail, if the HTTP Server serves a self-signed (self-signed CA) certificate.

### Use case

Currently I just `cat my.crt >> netbox/venv/python*.*/certifi/cacert.pem`
The venv does not persist after an upgrade, so I have to do this after every update.
It would be convenient to have a custom cert storage that persists.

**Comment by Vivida1** [comment]
What seems to work if you use Ubuntu (24.04) and docker-compose:

Install the CA into the OS:

``` bash
vim /usr/local/share/ca-certificates/my-root-ca.crt
update-ca-certificates
```

Mount the bundle into the container and tell Python requests via env to use the bundle:

``` yaml
  netbox:
    image: docker.io/netboxcommunity/netbox:v4.0-2.9.1
    volumes:
    - /etc/ssl:/etc/ssl:ro
   # [...]
    environment:
      REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
```
