### ISSUE TITLE
SSO icon is not resized since Netbox 4.1.2

### ISSUE THREAD

**Issue by Fredouye** [netbox-community/netbox#17644]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.2

### Python Version

3.12

### Steps to Reproduce

Hi

Netbox Docker is installed using this command :

```bash
# git clone -b release https://github.com/netbox-community/netbox-docker.git .
```

`docker-compose.override.yml` :

```yaml
services:
  netbox:
    image: netboxcommunity/netbox:v4.1.1
    volumes:
      - ./my-conf.py:/etc/netbox/config/extra.py:z,ro
    ports:
      - 18000:8080

  netbox-worker:
    image: netboxcommunity/netbox:v4.1.1

  netbox-housekeeping:
    image: netboxcommunity/netbox:v4.1.1
```

`my-conf.py` :

```py
# Keycloak
REMOTE_AUTH_ENABLED=True
REMOTE_AUTH_BACKEND="social_core.backends.open_id_connect.OpenIdConnectAuth"
SOCIAL_AUTH_OIDC_ENDPOINT="https://auth.home.lab/realms/home.lab"
SOCIAL_AUTH_OIDC_KEY="Netbox"
SOCIAL_AUTH_OIDC_SECRET="xxxxxxxxxxxxxxxxxxxxxxxx"
SOCIAL_AUTH_OIDC_SCOPE = ["openid", "profile", "email", "roles"]
SOCIAL_AUTH_VERIFY_SSL=True
SOCIAL_AUTH_OIDC_USERNAME_KEY="preferred_username"

SOCIAL_AUTH_BACKEND_ATTRS = {
    'oidc': ("SSO", "https://raw.githubusercontent.com/keycloak/keycloak-misc/refs/heads/main/logo/icon.svg"),
}
```

The https://raw.githubusercontent.com/keycloak/keycloak-misc/refs/heads/main/logo/icon.svg icon is `167x151` pixels.

With Netbox 4.1.1, the SSO icon is properly rendered, whereas with Netbox 4.1.2, the SSO icon is not resized.

### Expected Behavior

SSO icon should be resized (which is the case with Netbox 4.1.1) :

<img width="1211" alt="Netbox 4.1.1" src="https://github.com/user-attachments/assets/11b87ab9-06fb-4b4c-8d89-bdfbc13a6e7f">

### Observed Behavior

SSO icon is not resized with Netbox 4.1.2 :

<img width="1194" alt="Netbox 4.1.2" src="https://github.com/user-attachments/assets/6b95f123-972a-40dc-af81-668e8974333b">

All tests were made with Chrome 129 / macOS, in incognito mode.
