### ISSUE TITLE
Bulk import doesn't create module bay template from module type YAML

### ISSUE THREAD

**Issue by FabryUr** [netbox-community/netbox#17676]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.3

### Python Version

3.12

### Steps to Reproduce

1. Write a module type YAML, which contains module bays (similar to interfaces or as you do with device types)
2. Use the bulkimport function on the GUI and upload it to the module types. 

Here is the YAML, that I tried:
```
---
manufacturer: Cisco
model: ASR1000-SIP40
part_number: ASR1000-SIP40
module-bays:
  - name: Slot 1
    label: Expansion 1
    position: 0
  - name: Slot 2
    label: Expansion 2
    position: 1
  - name: Slot 3
    label: Expansion 3
    position: 2
  - name: Slot 4
    label: Expansion 4
    position: 3
```

### Expected Behavior

It should create the module-bay templates as it does with interfaces.

### Observed Behavior

It creates the module type without the module bay information. Of course you can add them with the "add component" button, but if you have 100 modular cards, it is not ideal.
![kép_2024-10-04_092505326](https://github.com/user-attachments/assets/cb1af6fb-0d97-4524-aafe-692d5c4e4c26)
