### ISSUE TITLE
Improve sidebar UX

### ISSUE THREAD

**Issue by patrickfnielsen** [netbox-community/netbox#17675]
### NetBox version

v4.1.3

### Feature type

Change to existing functionality

### Proposed functionality

I propose the following changes to the sidebar:
- Indentation of sub menu items
- ~~Making it collapsible again (I was told there was an issue for this, but I could not find it)~~ (see https://github.com/netbox-community/netbox/issues/16392)

A mockup of indentation could look like this:
![image](https://github.com/user-attachments/assets/fc41ba03-8803-4149-b612-66e51e44ef66)

Using the following css:
```css
.navbar-vertical.navbar-expand-lg .navbar-collapse .text-secondary {
  padding-left: 2.8rem;
}

.dropdown-item a.d-inline-flex.flex-fill.py-1  {
  padding-left: 2.6rem;
}
```

### Use case

- Less reasoning needed as the indentation would clearly show where the sub menu items belong.
- ~~Restores functionality from NetBox 3.7, that is missed.~~ (see https://github.com/netbox-community/netbox/issues/16392)

### Database changes

None

### External dependencies

None
