### ISSUE TITLE
IPSec-Proposal optional field is required when sending HTTP Post request via API

### ISSUE THREAD

**Issue by Toosaman** [netbox-community/netbox#18271]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.10

### Python Version

3.10

### Steps to Reproduce

1. Trying to send HTTP POST request to API endpoint:
/api/vpn/ipsec-proposals/
```
{
'name': 'aes-192-gcm_3600',
'encryption_algorithm': 'aes-192-gcm',
'sa_lifetime_seconds': '3600'
}
```

### Expected Behavior

Got HTTP status code 201, which means that the object was successfully created.

### Observed Behavior

Got the error:

```
  allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
  api_version: '4.1'
  connection: close
  content: '{"authentication_algorithm":["This field is required."]}'
  json:
    authentication_algorithm:
    - This field is required.
```
