### ISSUE TITLE
Ansible netbox.netbox.netbox_vm_interface does not add MAC address

### ISSUE THREAD

**Issue by boredomwontgetus** [netbox-community/netbox#18787]
### Deployment Type

Self-hosted

### NetBox Version

v4.2.4

### Python Version

3.10

### Steps to Reproduce

```
 - name: Create primary interface and assign to VM
    netbox.netbox.netbox_vm_interface:
      netbox_url: http://local.local
      netbox_token: mytoken
      data:
        virtual_machine: vm01
        name: ens3
        mac_address: "50:20:10:30:AA:BB"
        enabled: true
      state: present
```
This creates the interface just fine but does not add the MAC. 

Do i have to add the MAC to Netbox before using this module? If so, what ansible module would i use for that?

### Expected Behavior

The Ansible module [netbox.netbox.netbox_vm_interface](https://docs.ansible.com/ansible/latest/collections/netbox/netbox/netbox_vm_interface_module.html#ansible-collections-netbox-netbox-netbox-vm-interface-module)  adds the mac address to an interface.

### Observed Behavior

Every ansible run results in state "changed" unless the MAC address is added to Netbox manually. So it somehow understands that the MAC is missing in Netbox yet fails silently to add it.
