### ISSUE TITLE
Implement subslot numbers for devices

### ISSUE THREAD

**Issue by lucatortiglione** [netbox-community/netbox#19280]
### NetBox version

v4.2.8

### Feature type

Data model extension

### Proposed functionality

Hi!
There are some Cisco devices such as ASR 9006,
where for every linecard you can install 2 modules,so you have

TenGigabitEthernet rack/slot 1/subslot 0/port
TenGigabitEthernet rack/slot 1/subslot 1/port

So theorically same module number (slot 1) and 2 subslots.

Usually subslot can be 0 and 1

### Use case

Better management of devices

**Comment by sleepinggenius2** [comment]
In your example, the ASR 9006 does not inherently support installing two modules for every linecard. You first need to insert a MOD linecard, like an A9K-MOD200-TR. So you would model that as a module with two module bays to support the daughtercards, then you would models the required MPA modules to put in those bays.

**Comment by lucatortiglione** [comment]
> In your example, the ASR 9006 does not inherently support installing two modules for every linecard. You first need to insert a MOD linecard, like an A9K-MOD200-TR. So you would model that as a module with two module bays to support the daughtercards, then you would models the required MPA modules to put in those bays.

Mmmh any suggestion how to manage this device ?

**Comment by sleepinggenius2** [comment]
Below are some device and module type definitions from our environment. I hope that helps.

ASR-9006 Device
```yaml
manufacturer: Cisco
model: ASR-9006
slug: cisco-asr-9006
description: Cisco ASR 9006 Router
default_platform: Cisco IOS XR
part_number: ASR-9006
u_height: 10.0
is_full_depth: true
weight: 87.5
weight_unit: lb
module-bays:
- name: Fan Tray Slot 0
  label: ''
  position: 0/FT0
  description: ASR9K Fan Tray Slot
- name: Fan Tray Slot 1
  label: ''
  position: 0/FT1
  description: ASR9K Fan Tray Slot
- name: Line Card Slot 0
  label: '0'
  position: 0/0
  description: ASR9K Line Card Slot
- name: Line Card Slot 1
  label: '1'
  position: 0/1
  description: ASR9K Line Card Slot
- name: Line Card Slot 2
  label: '2'
  position: 0/2
  description: ASR9K Line Card Slot
- name: Line Card Slot 3
  label: '3'
  position: 0/3
  description: ASR9K Line Card Slot
- name: Power Tray Slot 0
  label: ''
  position: 0/PT0
  description: ASR9K Power Tray Slot
- name: RouteProcessor Slot 0
  label: RSP 0
  position: 0/RSP0
  description: ASR9K Route Processor Slot
- name: RouteProcessor Slot 1
  label: RSP 1
  position: 0/RSP1
  description: ASR9K Route Processor Slot
```

A9K-MOD200-TR Module
```yaml
manufacturer: Cisco
model: A9K-MOD200-TR
part_number: A9K-MOD200-TR
description: 200G Modular Linecard, Packet Transport Optimized
module-bays:
- name: Subslot 0
  label: '0'
  position: '0'
- name: Subslot 1
  label: '1'
  position: '1'
```

A9K-MPA-8X10GE Module
```yaml
manufacturer: Cisco
model: A9K-MPA-8X10GE
part_number: A9K-MPA-8X10GE
description: ASR 9000 8-port 10-Gigabit Ethernet Modular Port Adapter, requires SFP+ optics
weight: 1.75
weight_unit: lb
interfaces:
- name: TenGigE{module}/{module}/0
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '0'
- name: TenGigE{module}/{module}/1
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '1'
- name: TenGigE{module}/{module}/2
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '2'
- name: TenGigE{module}/{module}/3
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '3'
- name: TenGigE{module}/{module}/4
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '4'
- name: TenGigE{module}/{module}/5
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '5'
- name: TenGigE{module}/{module}/6
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '6'
- name: TenGigE{module}/{module}/7
  type: 10gbase-x-sfpp
  enabled: true
  mgmt_only: false
  label: '7'
```
