### ISSUE TITLE
Update pyproject.toml with a [project] stanza

### ISSUE THREAD

**Issue by hblandford** [netbox-community/netbox#19535]
### NetBox version

v4.3.1

### Feature type

Other

### Proposed functionality

Include a project stanza in the pyproject.toml file to assist users who would like to run uv.

This would not have to be comprehensive, but it could be useful to include some information.
I have not added the dependencies section to file as that is easily sorted from the requirements.txt but that could be included as well.

I have inserted it after the comment and before the [tool.black] stanza:

```toml
[project]
name = "netbox"
version = "4.3.1"
description = """\
NetBox exists to empower network engineers. Since its release in 2016, it has become the go-to solution for modeling\
 and documenting network infrastructure for thousands of organizations worldwide. As a successor to legacy IPAM and\
 DCIM applications, NetBox provides a cohesive, extensive, and accessible data model for all things networked.\
 By providing a single robust user interface and programmable APIs for everything from cable maps to device\
 configurations, NetBox serves as the central source of truth for the modern network.
"""
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [{ name = "NetBox Community" }]
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
]

[project.urls]
Homepage = "https://netbox.readthedocs.io/"
Source = "https://github.com/netbox-community/netbox"
Documentation = "https://docs.netbox.dev/"
```

### Use case

If users wish to use uv for their virtual environment, they have to edit the pyproject.toml file to include the [project] section or uv fails when running any commands:

root@netbox:/opt/netbox# uv run python --version
error: No `project` table found in: `/opt/netbox/pyproject.toml`

### Database changes

None

### External dependencies

None
