### ISSUE TITLE
Prefix matching query does not exist.

### ISSUE THREAD

**Issue by litebito** [netbox-community/netbox#19784]
### Deployment Type

Self-hosted

### NetBox Version

v4.3.1

### Python Version

3.12

### Steps to Reproduce

A/ Upgrade from 4.2.8 to 4.3.1:

```
sudo git checkout v4.3.0
sudo PYTHON=/usr/bin/python3.12 /opt/netbox/upgrade.sh
sudo systemctl restart netbox netbox-rq
```

B/ In Netbox UI
1) goto IPAM, click on an IP address
This generates the following error:

```
<class 'ipam.models.ip.Prefix.DoesNotExist'>

Prefix matching query does not exist.

Python version: 3.12.10
NetBox version: 4.3.1
Plugins: 
  aggregatron: 0.1
  netbox_attachments: 8.0.4
  netbox_device_view: 0.1.9
  netbox_dns: 1.3.3
  netbox_documents: 0.7.3
  netbox_floorplan: 0.7.0
  netbox_inventory: 2.4.0
  netbox_ip_monitor: 0.0.1
  netbox_ipcalculator: 1.4.10
  netbox_metatype_importer: 0.7.0
  netbox_qrcode: 0.0.18
  netbox_reorder_rack: 1.1.3
  netbox_security: 1.2.2
  netbox_topology_plugin: 0.14.3
  netbox_topology_views: 4.3.0
```

OR 
2) got to devices and click on a device 

```
<class 'django.core.exceptions.ValidationError'>

['Invalid IP address format: devicename01']

Python version: 3.12.10
NetBox version: 4.3.1
Plugins: 
  aggregatron: 0.1
  netbox_attachments: 8.0.4
  netbox_device_view: 0.1.9
  netbox_dns: 1.3.3
  netbox_documents: 0.7.3
  netbox_floorplan: 0.7.0
  netbox_inventory: 2.4.0
  netbox_ip_monitor: 0.0.1
  netbox_ipcalculator: 1.4.10
  netbox_metatype_importer: 0.7.0
  netbox_qrcode: 0.0.18
  netbox_reorder_rack: 1.1.3
  netbox_security: 1.2.2
  netbox_topology_plugin: 0.14.3
  netbox_topology_views: 4.3.0

```

### Expected Behavior

Go to the details page of the clicked item

### Observed Behavior

1) goto IPAM, click on an IP address
This generates the following error:

```
<class 'ipam.models.ip.Prefix.DoesNotExist'>

Prefix matching query does not exist.

Python version: 3.12.10
NetBox version: 4.3.1
Plugins: 
  aggregatron: 0.1
  netbox_attachments: 8.0.4
  netbox_device_view: 0.1.9
  netbox_dns: 1.3.3
  netbox_documents: 0.7.3
  netbox_floorplan: 0.7.0
  netbox_inventory: 2.4.0
  netbox_ip_monitor: 0.0.1
  netbox_ipcalculator: 1.4.10
  netbox_metatype_importer: 0.7.0
  netbox_qrcode: 0.0.18
  netbox_reorder_rack: 1.1.3
  netbox_security: 1.2.2
  netbox_topology_plugin: 0.14.3
  netbox_topology_views: 4.3.0
```

OR 
2) got to devices and click on a device 

```
<class 'django.core.exceptions.ValidationError'>

['Invalid IP address format: devicename01']

Python version: 3.12.10
NetBox version: 4.3.1
Plugins: 
  aggregatron: 0.1
  netbox_attachments: 8.0.4
  netbox_device_view: 0.1.9
  netbox_dns: 1.3.3
  netbox_documents: 0.7.3
  netbox_floorplan: 0.7.0
  netbox_inventory: 2.4.0
  netbox_ip_monitor: 0.0.1
  netbox_ipcalculator: 1.4.10
  netbox_metatype_importer: 0.7.0
  netbox_qrcode: 0.0.18
  netbox_reorder_rack: 1.1.3
  netbox_security: 1.2.2
  netbox_topology_plugin: 0.14.3
  netbox_topology_views: 4.3.0

```
