### ISSUE TITLE
Add User-Selectable Themes and a Dark Theme

### ISSUE THREAD

**Issue by ReK42** [netbox-community/netbox#3599]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.5

### Proposed Functionality
Add a dark theme to the user interface and allow the choice of theme to be selected and saved per-user. Potentially implement in a way which allows administrators to add more themes or customized versions of themes.

### Use Case
Dark themes reduce eye strain and I have modified my own installation of netbox to use a dark theme, however some users prefer light themes. Implementing a way for users to select their preferred theme would satisfy all parties, plus allow for theme modification without forking or otherwise editing the netbox installation.

### Database Changes
Add a theme preference field to the User model. The default theme can be set via the Django configuration file.

### External Dependencies
As an example for implementation, I have added the [Bootswatch Slate](https://bootswatch.com/3/slate/) theme to my installation. See the attached screenshot. This involved replacing the default static/css/bootstrap.min.css file and making the following modifications to base.css to touch up the styling of select2 and netbox itself:

```css
.footer {
    border-top: 1px solid #3e444c;
}
.table-headings th {
    background-color: #3e444c;
}
.text-muted {
    color: #c8c8c8;
}

.select2-container--bootstrap .select2-results__option {
    color: #272b30;
}
.select2-container--bootstrap .select2-results__option[aria-disabled=true] {
    color: #999;
}
.select2-container--bootstrap .select2-results__option[aria-selected=true] {
    background-color: #d6e4f0;
    cursor: not-allowed;
}
```
![2019-10-11_13-52-47](https://user-images.githubusercontent.com/4775937/66684238-6e9dd900-ec2e-11e9-8486-ce32cb1ecd14.png)
