### ISSUE TITLE
Import of Device Type strips comments

### ISSUE THREAD

**Issue by constantpinger** [netbox-community/netbox#4684]
### Environment
* Python version: any
* NetBox version: 2.8.1 & 2.8.4

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Add device type via YAML import that has comments. Simple example for testing:

```
manufacturer: Cisco
model: Switch_with_comments
slug: testSwitch
u_height: 1
is_full_depth: false
comments: disappear
interfaces:
- name: ge1/0/0
  type: 1000base-t
  mgmt_only: false

```

### Expected Behavior
New device type includes the comments

### Observed Behavior
All details except comments are imported correctly. Comments section is blank. 
No error shown.

### Notes
I only have access to a v2.8.1 environment (my production) and v2.8.4 ([netboxdemo.com](https://netboxdemo.com/)). This issue may have existed in prior releases.

This is my first bug report. Please feel free to suggest improvements.
