### ISSUE TITLE
Include device images in exported YAML

### ISSUE THREAD

**Issue by fernandolcx** [netbox-community/netbox#5366]
### Environment
* Python version: 3.9
* NetBox version: 2.9.9

### Proposed Functionality
Be able to import/export device models with their respective front/rear images.
Exported YAML will need to have an extra field containing their respective front/rear image, encoded in base64 (maybe?).

### Use Case
Currently, the exported YAML for device models already carries all physical/logical information, so their respecitve images will be a plus, when migrating/exporting data between installations.

### Database Changes
None that I'm aware of.

### External Dependencies
I think base64 is native in Python so no external library will be necessary.

**Comment by jeremystretch** [comment]
To be clear, you're proposing that we embed base64-encoded image data _within_ the YAML data? This would make these files incredibly difficult and tedious to modify by hand. It would also greatly complicate the logic and validation needed to import objects. Why not just reference the image by URL?

**Comment by fernandolcx** [comment]
> To be clear, you're proposing that we embed base64-encoded image data _within_ the YAML data? This would make these files incredibly difficult and tedious to modify by hand. 

I just use these YAML files to move data between installations so I never edit them, but for those who do I agree, It will be a mess.

> It would also greatly complicate the logic and validation needed to import objects. 

My initial proposal was to generate a single, consolidated file containing all the needed data to import.
If it's that complicated, we can consider exporting PNG/JPG files together with YAML file....

> Why not just reference the image by URL?

... and reference it locally, right?

**Comment by jeremystretch** [comment]
> but for those who do I agree, It will be a mess

IMO this alone is justification enough to not pursue this feature request.

> ... and reference it locally, right?

Please clarify what you're asking.

**Comment by fernandolcx** [comment]
When we export device models, their respective images are not included. So when importing these files in new installations, we need to have these images on disk and upload them, by hand, one by one.

What I'm asking is if it's possible to include these images when exporting, be them encoded within YAML or separated PNG/JPG/SVG files.

**Comment by jeremystretch** [comment]
I understand that. I'm not sure what you mean by the line quoted above.

**Comment by fernandolcx** [comment]
> I understand that. I'm not sure what you mean by the line quoted above.

Something like this:
```yaml
---
 manufacturer: 3Com
 model: SuperStack 3 4500 PWR
 slug: superstack-3-4500-pwr
 part_number: 3CR17572-91
 u_height: 1
 images: 
 - side: "front"
   file: "3com-4500-pwr_front.png"
   size: 64241
   md5sum: "d37740dbf9fdba01723074357919f991"
   format: "png"
 - side: "rear"
   file: "3com-4500-pwr_rear.png"
   size: 64587
   md5sum: "5478540dbf9fdba0172385757919f991"
   format: "png"
```
When I say "locally" I mean that the image is stored locally rather in a remote location, and it needs to be uploaded together with YAML file.
