### ISSUE TITLE
NetBox 2.10.3 - Server Error "ObjectChange.user" must be a "User"

### ISSUE THREAD

**Issue by dsg-anthony** [netbox-community/netbox#5609]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.3

### Steps to Reproduce
(GUI and API via Ansible module)
1. Create VM with 1 NIC
2. Create a IPv4  Address
3. Assign IPv4 address to NIC
2. Set IPv4 to primary IP on VM 

```yaml
- name: set primary IP4
     netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{url}}"
        netbox_token: "{{token}}"
        validate_certs: no
   data:
     name: "{{server_name}}"
     primary_ip4: "{{IP}}"
```

### Expected Behavior
IPv4 to be set as primary IP

### Observed Behavior
1 out of every 5 or so request will error out. We have noticed other calls failing with the same error but this action is the most common that we have seen fail. This if after we upgraded to 2.10.3
Error:
```
<class 'ValueError'>

Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f0ea5454da0>>": "ObjectChange.user" must be a "User" instance.

Python version: 3.6.8
NetBox version: 2.10.3
```
![image](https://user-images.githubusercontent.com/43544235/104238744-6f23b180-5427-11eb-845c-ba5e43fca99e.png)
