### ISSUE TITLE
Device type import fails silently

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#6695]
### NetBox version

v2.11.7

### Python version

3.6

### Steps to Reproduce

1. Create a manufacturer called "Unknown"
2. Go to Devices > Device Types > Import (`/dcim/device-types/import/`)
3. Paste in the following YAML and click Submit

```
manufacturer: Unknown
model: Packet Shooter 9000
slug: packet-shooter-9000
u_height: 1
front-ports:
  - name: F1
    description: foo
    label: FP1
rear-ports:
  - name: R1
    type: 8p8c
    description: bar
    label: RP1
```

### Expected Behavior

Error returned showing data validation problem (some things are missing, like front-port type and front-port to rear-port association)

### Observed Behavior

GUI goes to `/dcim/device-types/28/` but reports "The requested page does not exist."

This is not a caching bug:
* invalidating the cache makes no difference
* `select * from dcim_devicetype where id=28;` returns no rows
