### ISSUE TITLE
Search bar object type dropdown menu truncated on small screens

### ISSUE THREAD

**Issue by koh6uawi** [netbox-community/netbox#6977]
### NetBox version

v3.0-beta2

### Python version

3.9

### Steps to Reproduce

Use a small screen (eg. 1440×900).

### Expected Behavior

One should be able to choose the object type in the search bar even it they are using a small screen (maybe by removing the sticky class attribute on the search bar, or by making the dropdown menu scrollable?).

### Observed Behavior

When using a small screen, the dropdown menu is truncated (as the search bar is sticky, the end of the menu can't be viewed even when scrolling).

![Screen Shot 2021-08-17 at 15 24 20](https://user-images.githubusercontent.com/89084173/129734125-63f4a566-20b4-4f37-ad93-97a5750d4ab5.png)

**Comment by jeremystretch** [comment]
Interestingly, we do have an accommodation in place for this already, however it's bound to the screen's width rather than its height.

```css
    // Object Selector Dropdown Menu
    .search-obj-selector {
      @include media-breakpoint-down(lg) {
        // Limit the height and enable scrolling on mobile devices.
        max-height: 70vh;
        overflow-y: auto;
      }
```

IMO it's reasonable to always restrict the dropdown's relative height regardless of screen size.
