### ISSUE TITLE
Device export of module bays excludes position

### ISSUE THREAD

**Issue by ekrichbaum** [netbox-community/netbox#9100]
### NetBox version

v3.2.0

### Python version

3.10

### Steps to Reproduce

1. From Device Types List, Select Export, All Data (YAML).
2. Find device and module-bays:
```
module-bays:
- name: IO Module 1
  label: ''
  description: ''
- name: IO Module 2
  label: ''
  description: ''
```

Position element is not exported.

### Expected Behavior

Position should be exported for module bays.

### Observed Behavior

Position is not exported.
