### ISSUE TITLE
Device Type Export YAML indenting behaviour

### ISSUE THREAD

**Issue by ekrichbaum** [netbox-community/netbox#9101]
### NetBox version

v3.2.0

### Python version

3.10

### Steps to Reproduce

1. From Device Type List, Select Export, All Data (YAML)

### Expected Behavior

```yaml
console-ports:
  - name: Con0
    type: rj-45
    label: ''
    description: ''
```

Additional indent of 2 spaces for each sub element. (allow for direct paste for devicetype library item without edit of each line)

Potentially, also drop blank items out (also for allow to direct paste for devicetype library without removal).

### Observed Behavior

```yaml
console-ports:
- name: Con0
  type: rj-45
  label: ''
  description: ''
```

Those don't format well here.
