### ISSUE TITLE
support color attribute on module type and device type import and export

### ISSUE THREAD

**Issue by oasys** [netbox-community/netbox#9906]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

When importing module types via the web interface (Devices -> Module Types -> Import), allow specifying `color` attribute for front and rear ports.   Also, when exporting module types via the web interface (Devices -> Module Types -> Export -> All Data (YAML)) include the `color` attribute for front and rear ports, if defined.

An example import file:

```yaml
manufacturer: Generic
model: test-device
part_number: ''
comments: ''
front-ports:
- name: '1'
  type: lc
  rear_port: '1'
  rear_port_position: 1
  label: ''
  color: '3f51b5'
  description: ''
- name: '2'
  type: lc
  rear_port: '1'
  rear_port_position: 2
  label: ''
  color: '3f51b5'
  description: ''
rear-ports:
- name: '1'
  type: mpo
  positions: 2
  label: ''
  color: '000000'
  description: ''
```

Currently, it appears that the `color` field is ignored.

An export of that module type does not show the color.

```yaml
manufacturer: Generic
model: test-device
part_number: ''
comments: ''
front-ports:
- name: '1'
  type: lc
  rear_port: '1'
  rear_port_position: 1
  label: ''
  description: ''
- name: '2'
  type: lc
  rear_port: '1'
  rear_port_position: 2
  label: ''
  description: ''
rear-ports:
- name: '1'
  type: mpo
  positions: 2
  label: ''
  description: ''
```

I see similar behavior with device types.

I'm not sure to consider this omission a bug or not, so am submitting as a FR.

### Use case

It is useful to create a library of device type and module types outside of netbox for easy import into new installations.  This would allow the inclusion of the color field in the objects in this library.

### Database changes

none

### External dependencies

none
